namespace Falco.Markup

[<AutoOpen>]
module Html =
    let inline _html attr content = Elem.html attr content
    let inline _base attr = Elem.base' attr
    let inline _head attr content = Elem.head attr content
    let inline _link attr = Elem.link attr
    let inline _meta attr = Elem.meta attr
    let inline _style attr content = Elem.style attr content
    let inline _title attr content = Elem.title attr content
    let inline _body attr content = Elem.body attr content
    let inline _address attr content = Elem.address attr content
    let inline _article attr content = Elem.article attr content
    let inline _aside attr content = Elem.aside attr content
    let inline _footer attr content = Elem.footer attr content
    let inline _header attr content = Elem.header attr content
    let inline _h1 attr content = Elem.h1 attr content
    let inline _h2 attr content = Elem.h2 attr content
    let inline _h3 attr content = Elem.h3 attr content
    let inline _h4 attr content = Elem.h4 attr content
    let inline _h5 attr content = Elem.h5 attr content
    let inline _h6 attr content = Elem.h6 attr content
    let inline _main attr content = Elem.main attr content
    let inline _nav attr content = Elem.nav attr content
    let inline _section attr content = Elem.section attr content
    let inline _blockquote attr content = Elem.blockquote attr content
    let inline _dd attr content = Elem.dd attr content
    let inline _div attr content = Elem.div attr content
    let inline _dl attr content = Elem.dl attr content
    let inline _dt attr content = Elem.dt attr content
    let inline _figcaption attr content = Elem.figcaption attr content
    let inline _figure attr content = Elem.figure attr content
    let inline _hr attr = Elem.hr attr
    let inline _li attr content = Elem.li attr content
    let inline _menu attr content = Elem.menu attr content
    let inline _ol attr content = Elem.ol attr content
    let inline _p attr content = Elem.p attr content
    let inline _pre attr content = Elem.pre attr content
    let inline _ul attr content = Elem.ul attr content
    let inline _a attr content = Elem.a attr content
    let inline _abbr attr content = Elem.abbr attr content
    let inline _b attr content = Elem.b attr content
    let inline _bdi attr content = Elem.bdi attr content
    let inline _bdo attr content = Elem.bdo attr content
    let inline _br attr = Elem.br attr
    let inline _cite attr content = Elem.cite attr content
    let inline _code attr content = Elem.code attr content
    let inline _data attr content = Elem.data attr content
    let inline _dfn attr content = Elem.dfn attr content
    let inline _em attr content = Elem.em attr content
    let inline _i attr content = Elem.i attr content
    let inline _kbd attr content = Elem.kbd attr content
    let inline _mark attr content = Elem.mark attr content
    let inline _q attr content = Elem.q attr content
    let inline _rp attr content = Elem.rp attr content
    let inline _rt attr content = Elem.rt attr content
    let inline _ruby attr content = Elem.ruby attr content
    let inline _s attr content = Elem.s attr content
    let inline _samp attr content = Elem.samp attr content
    let inline _small attr content = Elem.small attr content
    let inline _span attr content = Elem.span attr content
    let inline _strong attr content = Elem.strong attr content
    let inline _sub attr content = Elem.sub attr content
    let inline _sup attr content = Elem.sup attr content
    let inline _time attr content = Elem.time attr content
    let inline _u attr content = Elem.u attr content
    let inline _var attr content = Elem.var attr content
    let inline _wbr attr = Elem.wbr attr
    let inline _area attr content = Elem.area attr content
    let inline _audio attr content = Elem.audio attr content
    let inline _img attr = Elem.img attr
    let inline _map attr content = Elem.map attr content
    let inline _track attr = Elem.track attr
    let inline _video attr content = Elem.video attr content
    let inline _embed attr = Elem.embed attr
    let inline _iframe attr content = Elem.iframe attr content
    let inline _object attr content = Elem.object attr content
    let inline _picture attr content = Elem.picture attr content
    let inline _portal attr content = Elem.portal attr content
    let inline _source attr = Elem.source attr
    let inline _canvas attr content = Elem.canvas attr content
    let inline _noscript attr content = Elem.noscript attr content
    let inline _script attr content = Elem.script attr content
    let inline _del attr content = Elem.del attr content
    let inline _ins attr content = Elem.ins attr content
    let inline _caption attr content = Elem.caption attr content
    let inline _col attr = Elem.col attr
    let inline _colgroup attr content = Elem.colgroup attr content
    let inline _table attr content = Elem.table attr content
    let inline _tbody attr content = Elem.tbody attr content
    let inline _td attr content = Elem.td attr content
    let inline _tfoot attr content = Elem.tfoot attr content
    let inline _th attr content = Elem.th attr content
    let inline _thead attr content = Elem.thead attr content
    let inline _tr attr content = Elem.tr attr content
    let inline _button attr content = Elem.button attr content
    let inline _datalist attr content = Elem.datalist attr content
    let inline _fieldset attr content = Elem.fieldset attr content
    let inline _form attr content = Elem.form attr content
    let inline _input attr = Elem.input attr
    let inline _label attr content = Elem.label attr content
    let inline _legend attr content = Elem.legend attr content
    let inline _meter attr content = Elem.meter attr content
    let inline _optgroup attr content = Elem.optgroup attr content
    let inline _option attr content = Elem.option attr content
    let inline _output attr content = Elem.output attr content
    let inline _progress attr content = Elem.progress attr content
    let inline _select attr content = Elem.select attr content
    let inline _textarea attr content = Elem.textarea attr content
    let inline _control name attr labelElement = Elem.control name attr labelElement
    let inline _controlSelect name attr labelElement options = Elem.controlSelect name attr labelElement options
    let inline _controlTextarea name attr labelElement content = Elem.controlTextarea name attr labelElement content
    let inline _details attr content = Elem.details attr content
    let inline _dialog attr content = Elem.dialog attr content
    let inline _summary attr content = Elem.summary attr content
    let inline _slot attr content = Elem.slot attr content
    let inline _template attr content = Elem.template attr content
    let inline _math attr content = Elem.math attr content
    let inline _svg attr content = Elem.svg attr content

    let h1_ content = Text.h1 content
    let h2_ content = Text.h2 content
    let h3_ content = Text.h3 content
    let h4_ content = Text.h4 content
    let h5_ content = Text.h5 content
    let h6_ content = Text.h6 content
    let p_ content = Text.p content
    let dd_ content = Text.dd content
    let dt_ content = Text.dt content
    let abbr_ content = Text.abbr content
    let b_ content = Text.b content
    let bdi_ content = Text.bdi content
    let bdo_ content = Text.bdo content
    let cite_ content = Text.cite content
    let code_ content = Text.code content
    let data_ content = Text.data content
    let dfn_ content = Text.dfn content
    let em_ content = Text.em content
    let i_ content = Text.i content
    let kbd_ content = Text.kbd content
    let mark_ content = Text.mark content
    let q_ content = Text.q content
    let rp_ content = Text.rp content
    let rt_ content = Text.rt content
    let ruby_ content = Text.ruby content
    let s_ content = Text.s content
    let samp_ content = Text.samp content
    let small_ content = Text.small content
    let span_ content = Text.span content
    let strong_ content = Text.strong content
    let sub_ content = Text.sub content
    let sup_ content = Text.sup content
    let time_ content = Text.time content
    let u_ content = Text.u content
    let var_ content = Text.var content

    let inline __accept value = Attr.accept value
    let inline __acceptCharset value = Attr.acceptCharset value
    let inline __accesskey value = Attr.accesskey value
    let inline __action value = Attr.action value
    let inline __align value = Attr.align value
    let inline __allow value = Attr.allow value
    let inline __alt value = Attr.alt value
    let __async = Attr.async
    let inline __autocapitalize value = Attr.autocapitalize value
    let inline __autocomplete value = Attr.autocomplete value
    let __autofocus = Attr.autofocus
    let __autoplay = Attr.autoplay
    let inline __background value = Attr.background value
    let inline __bgcolor value = Attr.bgcolor value
    let inline __border value = Attr.border value
    let inline __buffered value = Attr.buffered value
    let inline __capture value = Attr.capture value
    let inline __challenge value = Attr.challenge value
    let inline __charset value = Attr.charset value
    let __checked = Attr.checked'
    let inline __cite value = Attr.cite value
    let inline __class value = Attr.class' value
    let inline __code value = Attr.code value
    let inline __codebase value = Attr.codebase value
    let inline __color value = Attr.color value
    let inline __cols value = Attr.cols value
    let inline __colspan value = Attr.colspan value
    let inline __content value = Attr.content value
    let inline __contenteditable value = Attr.contenteditable value
    let inline __contextmenu value = Attr.contextmenu value
    let __controls = Attr.controls
    let inline __coords value = Attr.coords value
    let inline __crossorigin value = Attr.crossorigin value
    let inline __csp value = Attr.csp value
    let inline __data value = Attr.data value
    let inline __dataAttr name value = Attr.dataAttr name value
    let inline __datetime value = Attr.datetime value
    let inline __decoding value = Attr.decoding value
    let __default = Attr.default'
    let __defer = Attr.defer
    let inline __dir value = Attr.dir value
    let inline __dirname value = Attr.dirname value
    let __disabled = Attr.disabled
    let inline __download value = Attr.download value
    let inline __draggable value = Attr.draggable value
    let inline __enctype value = Attr.enctype value
    let inline __enterkeyhint value = Attr.enterkeyhint value
    let inline __for value = Attr.for' value
    let inline __form value = Attr.form value
    let inline __formaction value = Attr.formaction value
    let inline __formenctype value = Attr.formenctype value
    let inline __formmethod value = Attr.formmethod value
    let __formnovalidate = Attr.formnovalidate
    let inline __formtarget value = Attr.formtarget value
    let inline __headers value = Attr.headers value
    let inline __height value = Attr.height value
    let __hidden = Attr.hidden
    let inline __high value = Attr.high value
    let inline __href value = Attr.href value
    let inline __hreflang value = Attr.hreflang value
    let inline __httpEquiv value = Attr.httpEquiv value
    let inline __icon value = Attr.icon value
    let inline __id value = Attr.id value
    let inline __importance value = Attr.importance value
    let inline __integrity value = Attr.integrity value
    let inline __inputmode value = Attr.inputmode value
    let __ismap = Attr.ismap
    let inline __itemprop value = Attr.itemprop value
    let inline __keytype value = Attr.keytype value
    let inline __kind value = Attr.kind value
    let inline __label value = Attr.label value
    let inline __lang value = Attr.lang value
    let inline __loading value = Attr.loading value
    let inline __list value = Attr.list value
    let __loop = Attr.loop
    let inline __low value = Attr.low value
    let inline __max value = Attr.max value
    let inline __maxlength value = Attr.maxlength value
    let inline __minlength value = Attr.minlength value
    let inline __media value = Attr.media value
    let inline __method value = Attr.method value
    let inline __min value = Attr.min value
    let __multiple = Attr.multiple
    let __muted = Attr.muted
    let inline __name value = Attr.name value
    let __novalidate = Attr.novalidate
    let inline __open value = Attr.open' value
    let inline __optimum value = Attr.optimum value
    let inline __pattern value = Attr.pattern value
    let inline __ping value = Attr.ping value
    let inline __placeholder value = Attr.placeholder value
    let inline __poster value = Attr.poster value
    let inline __preload value = Attr.preload value
    let inline __radiogroup value = Attr.radiogroup value
    let __readonly = Attr.readonly
    let inline __referrerpolicy value = Attr.referrerpolicy value
    let inline __rel value = Attr.rel value
    let __required = Attr.required
    let __reversed = Attr.reversed
    let inline __role value = Attr.role value
    let inline __rows value = Attr.rows value
    let inline __rowspan value = Attr.rowspan value
    let inline __sandbox value = Attr.sandbox value
    let inline __scope value = Attr.scope value
    let __selected = Attr.selected
    let inline __shape value = Attr.shape value
    let inline __size value = Attr.size value
    let inline __sizes value = Attr.sizes value
    let inline __slot value = Attr.slot value
    let inline __span value = Attr.span value
    let inline __spellcheck value = Attr.spellcheck value
    let inline __src value = Attr.src value
    let inline __srcdoc value = Attr.srcdoc value
    let inline __srclang value = Attr.srclang value
    let inline __srcset value = Attr.srcset value
    let inline __start value = Attr.start value
    let inline __step value = Attr.step value
    let inline __style value = Attr.style value
    let inline __tabindex value = Attr.tabindex value
    let inline __target value = Attr.target value
    let inline __title value = Attr.title value
    let inline __translate value = Attr.translate value
    let inline __type value = Attr.type' value
    let inline __usemap value = Attr.usemap value
    let inline __value value = Attr.value value
    let inline __width value = Attr.width value
    let inline __wrap value = Attr.wrap value
    let __enctypeForm = Attr.enctypeForm
    let __enctypeMultipart = Attr.enctypeMultipart
    let __methodPost = Attr.methodPost
    let __methodGet = Attr.methodGet
    let __methodDialog = Attr.methodDialog
    let __targetSelf = Attr.targetSelf
    let __targetBlank = Attr.targetBlank
    let __targetParent = Attr.targetParent
    let __targetTop = Attr.targetTop
    let __targetUnfencedTop = Attr.targetUnfencedTop
    let __typeButton = Attr.typeButton
    let __typeCheckbox = Attr.typeCheckbox
    let __typeColor = Attr.typeColor
    let __typeDate = Attr.typeDate
    let __typeDatetimeLocal = Attr.typeDatetimeLocal
    let __typeEmail = Attr.typeEmail
    let __typeFile = Attr.typeFile
    let __typeHidden = Attr.typeHidden
    let __typeImage = Attr.typeImage
    let __typeMonth = Attr.typeMonth
    let __typeNumber = Attr.typeNumber
    let __typePassword = Attr.typePassword
    let __typeRadio = Attr.typeRadio
    let __typeRange = Attr.typeRange
    let __typeReset = Attr.typeReset
    let __typeSearch = Attr.typeSearch
    let __typeSubmit = Attr.typeSubmit
    let __typeTel = Attr.typeTel
    let __typeText = Attr.typeText
    let __typeTime = Attr.typeTime
    let __typeUrl = Attr.typeUrl
    let __typeWeek = Attr.typeWeek
    let inline __onabort value = Attr.onabort value
    let inline __onafterprint value = Attr.onafterprint value
    let inline __onanimationend value = Attr.onanimationend value
    let inline __onanimationiteration value = Attr.onanimationiteration value
    let inline __onanimationstart value = Attr.onanimationstart value
    let inline __onbeforeprint value = Attr.onbeforeprint value
    let inline __onbeforeunload value = Attr.onbeforeunload value
    let inline __onblur value = Attr.onblur value
    let inline __oncanplay value = Attr.oncanplay value
    let inline __oncanplaythrough value = Attr.oncanplaythrough value
    let inline __onchange value = Attr.onchange value
    let inline __onclick value = Attr.onclick value
    let inline __oncontextmenu value = Attr.oncontextmenu value
    let inline __oncopy value = Attr.oncopy value
    let inline __oncut value = Attr.oncut value
    let inline __ondblclick value = Attr.ondblclick value
    let inline __ondrag value = Attr.ondrag value
    let inline __ondragend value = Attr.ondragend value
    let inline __ondragenter value = Attr.ondragenter value
    let inline __ondragleave value = Attr.ondragleave value
    let inline __ondragover value = Attr.ondragover value
    let inline __ondragstart value = Attr.ondragstart value
    let inline __ondrop value = Attr.ondrop value
    let inline __ondurationchange value = Attr.ondurationchange value
    let inline __onemptied value = Attr.onemptied value
    let inline __onended value = Attr.onended value
    let inline __onerror value = Attr.onerror value
    let inline __onfocus value = Attr.onfocus value
    let inline __onformchange value = Attr.onformchange value
    let inline __onforminput value = Attr.onforminput value
    let inline __onfocusin value = Attr.onfocusin value
    let inline __onfocusout value = Attr.onfocusout value
    let inline __onfullscreenchange value = Attr.onfullscreenchange value
    let inline __onfullscreenerror value = Attr.onfullscreenerror value
    let inline __onhashchange value = Attr.onhashchange value
    let inline __oninput value = Attr.oninput value
    let inline __oninvalid value = Attr.oninvalid value
    let inline __onkeydown value = Attr.onkeydown value
    let inline __onkeypress value = Attr.onkeypress value
    let inline __onkeyup value = Attr.onkeyup value
    let inline __onload value = Attr.onload value
    let inline __onloadeddata value = Attr.onloadeddata value
    let inline __onloadedmetadata value = Attr.onloadedmetadata value
    let inline __onloadstart value = Attr.onloadstart value
    let inline __onmessage value = Attr.onmessage value
    let inline __onmousedown value = Attr.onmousedown value
    let inline __onmouseenter value = Attr.onmouseenter value
    let inline __onmouseleave value = Attr.onmouseleave value
    let inline __onmousemove value = Attr.onmousemove value
    let inline __onmouseover value = Attr.onmouseover value
    let inline __onmouseout value = Attr.onmouseout value
    let inline __onmouseup value = Attr.onmouseup value
    let inline __onmousewheel value = Attr.onmousewheel value
    let inline __onoffline value = Attr.onoffline value
    let inline __ononline value = Attr.ononline value
    let inline __onopen value = Attr.onopen value
    let inline __onpagehide value = Attr.onpagehide value
    let inline __onpageshow value = Attr.onpageshow value
    let inline __onpaste value = Attr.onpaste value
    let inline __onpause value = Attr.onpause value
    let inline __onplay value = Attr.onplay value
    let inline __onplaying value = Attr.onplaying value
    let inline __onpopstate value = Attr.onpopstate value
    let inline __onprogress value = Attr.onprogress value
    let inline __onratechange value = Attr.onratechange value
    let inline __onresize value = Attr.onresize value
    let inline __onreset value = Attr.onreset value
    let inline __onscroll value = Attr.onscroll value
    let inline __onsearch value = Attr.onsearch value
    let inline __onseeked value = Attr.onseeked value
    let inline __onseeking value = Attr.onseeking value
    let inline __onselect value = Attr.onselect value
    let inline __onshow value = Attr.onshow value
    let inline __onstalled value = Attr.onstalled value
    let inline __onstorage value = Attr.onstorage value
    let inline __onsubmit value = Attr.onsubmit value
    let inline __onsuspend value = Attr.onsuspend value
    let inline __ontimeupdate value = Attr.ontimeupdate value
    let inline __ontoggle value = Attr.ontoggle value
    let inline __ontouchcancel value = Attr.ontouchcancel value
    let inline __ontouchend value = Attr.ontouchend value
    let inline __ontouchmove value = Attr.ontouchmove value
    let inline __ontouchstart value = Attr.ontouchstart value
    let inline __ontransitionend value = Attr.ontransitionend value
    let inline __onunload value = Attr.onunload value
    let inline __onvolumechange value = Attr.onvolumechange value
    let inline __onwaiting value = Attr.onwaiting value
    let inline __onwheel value = Attr.onwheel value
