namespace Falco.Markup

[<AutoOpen>]
module Html =
    let inline _text content = Text.raw content
    let inline _textf template = Text.rawf template
    let inline _textEnc content = Text.enc content
    let inline _h1' content = Text.h1 content
    let inline _h2' content = Text.h2 content
    let inline _h3' content = Text.h3 content
    let inline _h4' content = Text.h4 content
    let inline _h5' content = Text.h5 content
    let inline _h6' content = Text.h6 content
    let inline _p' content = Text.p content
    let inline _dd' content = Text.dd content
    let inline _dt' content = Text.dt content
    let inline _abbr' content = Text.abbr content
    let inline _b' content = Text.b content
    let inline _bdi' content = Text.bdi content
    let inline _bdo' content = Text.bdo content
    let inline _cite' content = Text.cite content
    let inline _code' content = Text.code content
    let inline _data' content = Text.data content
    let inline _dfn' content = Text.dfn content
    let inline _em' content = Text.em content
    let inline _i' content = Text.i content
    let inline _kbd' content = Text.kbd content
    let inline _mark' content = Text.mark content
    let inline _q' content = Text.q content
    let inline _rp' content = Text.rp content
    let inline _rt' content = Text.rt content
    let inline _ruby' content = Text.ruby content
    let inline _s' content = Text.s content
    let inline _samp' content = Text.samp content
    let inline _small' content = Text.small content
    let inline _span' content = Text.span content
    let inline _strong' content = Text.strong content
    let inline _sub' content = Text.sub content
    let inline _sup' content = Text.sup content
    let inline _time' content = Text.time content
    let inline _u' content = Text.u content
    let inline _var' content = Text.var content

    let inline _html attr content = Elem.html attr content
    let inline _base attr = Elem.base' attr
    let inline _head attr content = Elem.head attr content
    let inline _link attr = Elem.link attr
    let inline _meta attr = Elem.meta attr
    let inline _style attr content = Elem.style attr content
    let inline _title attr content = Elem.title attr content
    let inline _body attr content = Elem.body attr content
    let inline _address attr content = Elem.address attr content
    let inline _article attr content = Elem.article attr content
    let inline _aside attr content = Elem.aside attr content
    let inline _footer attr content = Elem.footer attr content
    let inline _header attr content = Elem.header attr content
    let inline _h1 attr content = Elem.h1 attr content
    let inline _h2 attr content = Elem.h2 attr content
    let inline _h3 attr content = Elem.h3 attr content
    let inline _h4 attr content = Elem.h4 attr content
    let inline _h5 attr content = Elem.h5 attr content
    let inline _h6 attr content = Elem.h6 attr content
    let inline _main attr content = Elem.main attr content
    let inline _nav attr content = Elem.nav attr content
    let inline _section attr content = Elem.section attr content
    let inline _blockquote attr content = Elem.blockquote attr content
    let inline _dd attr content = Elem.dd attr content
    let inline _div attr content = Elem.div attr content
    let inline _dl attr content = Elem.dl attr content
    let inline _dt attr content = Elem.dt attr content
    let inline _figcaption attr content = Elem.figcaption attr content
    let inline _figure attr content = Elem.figure attr content
    let inline _hr attr = Elem.hr attr
    let inline _li attr content = Elem.li attr content
    let inline _menu attr content = Elem.menu attr content
    let inline _ol attr content = Elem.ol attr content
    let inline _p attr content = Elem.p attr content
    let inline _pre attr content = Elem.pre attr content
    let inline _ul attr content = Elem.ul attr content
    let inline _a attr content = Elem.a attr content
    let inline _abbr attr content = Elem.abbr attr content
    let inline _b attr content = Elem.b attr content
    let inline _bdi attr content = Elem.bdi attr content
    let inline _bdo attr content = Elem.bdo attr content
    let inline _br attr = Elem.br attr
    let inline _cite attr content = Elem.cite attr content
    let inline _code attr content = Elem.code attr content
    let inline _data attr content = Elem.data attr content
    let inline _dfn attr content = Elem.dfn attr content
    let inline _em attr content = Elem.em attr content
    let inline _i attr content = Elem.i attr content
    let inline _kbd attr content = Elem.kbd attr content
    let inline _mark attr content = Elem.mark attr content
    let inline _q attr content = Elem.q attr content
    let inline _rp attr content = Elem.rp attr content
    let inline _rt attr content = Elem.rt attr content
    let inline _ruby attr content = Elem.ruby attr content
    let inline _s attr content = Elem.s attr content
    let inline _samp attr content = Elem.samp attr content
    let inline _small attr content = Elem.small attr content
    let inline _span attr content = Elem.span attr content
    let inline _strong attr content = Elem.strong attr content
    let inline _sub attr content = Elem.sub attr content
    let inline _sup attr content = Elem.sup attr content
    let inline _time attr content = Elem.time attr content
    let inline _u attr content = Elem.u attr content
    let inline _var attr content = Elem.var attr content
    let inline _wbr attr = Elem.wbr attr
    let inline _area attr content = Elem.area attr content
    let inline _audio attr content = Elem.audio attr content
    let inline _img attr = Elem.img attr
    let inline _map attr content = Elem.map attr content
    let inline _track attr = Elem.track attr
    let inline _video attr content = Elem.video attr content
    let inline _embed attr = Elem.embed attr
    let inline _iframe attr content = Elem.iframe attr content
    let inline _object attr content = Elem.object attr content
    let inline _picture attr content = Elem.picture attr content
    let inline _portal attr content = Elem.portal attr content
    let inline _source attr = Elem.source attr
    let inline _canvas attr content = Elem.canvas attr content
    let inline _noscript attr content = Elem.noscript attr content
    let inline _script attr content = Elem.script attr content
    let inline _del attr content = Elem.del attr content
    let inline _ins attr content = Elem.ins attr content
    let inline _caption attr content = Elem.caption attr content
    let inline _col attr = Elem.col attr
    let inline _colgroup attr content = Elem.colgroup attr content
    let inline _table attr content = Elem.table attr content
    let inline _tbody attr content = Elem.tbody attr content
    let inline _td attr content = Elem.td attr content
    let inline _tfoot attr content = Elem.tfoot attr content
    let inline _th attr content = Elem.th attr content
    let inline _thead attr content = Elem.thead attr content
    let inline _tr attr content = Elem.tr attr content
    let inline _button attr content = Elem.button attr content
    let inline _datalist attr content = Elem.datalist attr content
    let inline _fieldset attr content = Elem.fieldset attr content
    let inline _form attr content = Elem.form attr content
    let inline _input attr = Elem.input attr
    let inline _label attr content = Elem.label attr content
    let inline _legend attr content = Elem.legend attr content
    let inline _meter attr content = Elem.meter attr content
    let inline _optgroup attr content = Elem.optgroup attr content
    let inline _option attr content = Elem.option attr content
    let inline _output attr content = Elem.output attr content
    let inline _progress attr content = Elem.progress attr content
    let inline _select attr content = Elem.select attr content
    let inline _textarea attr content = Elem.textarea attr content
    let inline _control name attr labelElement = Elem.control name attr labelElement
    let inline _controlSelect name attr labelElement options = Elem.controlSelect name attr labelElement options
    let inline _controlTextarea name attr labelElement content = Elem.controlTextarea name attr labelElement content
    let inline _details attr content = Elem.details attr content
    let inline _dialog attr content = Elem.dialog attr content
    let inline _summary attr content = Elem.summary attr content
    let inline _slot attr content = Elem.slot attr content
    let inline _template attr content = Elem.template attr content
    let inline _math attr content = Elem.math attr content
    let inline _svg attr content = Elem.svg attr content


    let inline _accept_ value = Attr.accept value
    let inline _acceptCharset_ value = Attr.acceptCharset value
    let inline _accesskey_ value = Attr.accesskey value
    let inline _action_ value = Attr.action value
    let inline _align_ value = Attr.align value
    let inline _allow_ value = Attr.allow value
    let inline _alt_ value = Attr.alt value
    let _async_ = Attr.async
    let inline _autocapitalize_ value = Attr.autocapitalize value
    let inline _autocomplete_ value = Attr.autocomplete value
    let _autofocus_ = Attr.autofocus
    let _autoplay_ = Attr.autoplay
    let inline _background_ value = Attr.background value
    let inline _bgcolor_ value = Attr.bgcolor value
    let inline _border_ value = Attr.border value
    let inline _buffered_ value = Attr.buffered value
    let inline _capture_ value = Attr.capture value
    let inline _challenge_ value = Attr.challenge value
    let inline _charset_ value = Attr.charset value
    let _checked_ = Attr.checked'
    let inline _cite_ value = Attr.cite value
    let inline _class_ value = Attr.class' value
    let inline _code_ value = Attr.code value
    let inline _codebase_ value = Attr.codebase value
    let inline _color_ value = Attr.color value
    let inline _cols_ value = Attr.cols value
    let inline _colspan_ value = Attr.colspan value
    let inline _content_ value = Attr.content value
    let inline _contenteditable_ value = Attr.contenteditable value
    let inline _contextmenu_ value = Attr.contextmenu value
    let _controls_ = Attr.controls
    let inline _coords_ value = Attr.coords value
    let inline _crossorigin_ value = Attr.crossorigin value
    let inline _csp_ value = Attr.csp value
    let inline _data_ value = Attr.data value
    let inline _dataAttr_ name value = Attr.dataAttr name value
    let inline _datetime_ value = Attr.datetime value
    let inline _decoding_ value = Attr.decoding value
    let _default_ = Attr.default'
    let _defer_ = Attr.defer
    let inline _dir_ value = Attr.dir value
    let inline _dirname_ value = Attr.dirname value
    let _disabled_ = Attr.disabled
    let inline _download_ value = Attr.download value
    let inline _draggable_ value = Attr.draggable value
    let inline _enctype_ value = Attr.enctype value
    let inline _enterkeyhint_ value = Attr.enterkeyhint value
    let inline _for_ value = Attr.for' value
    let inline _form_ value = Attr.form value
    let inline _formaction_ value = Attr.formaction value
    let inline _formenctype_ value = Attr.formenctype value
    let inline _formmethod_ value = Attr.formmethod value
    let _formnovalidate_ = Attr.formnovalidate
    let inline _formtarget_ value = Attr.formtarget value
    let inline _headers_ value = Attr.headers value
    let inline _height_ value = Attr.height value
    let _hidden_ = Attr.hidden
    let inline _high_ value = Attr.high value
    let inline _href_ value = Attr.href value
    let inline _hreflang_ value = Attr.hreflang value
    let inline _httpEquiv_ value = Attr.httpEquiv value
    let inline _icon_ value = Attr.icon value
    let inline _id_ value = Attr.id value
    let inline _importance_ value = Attr.importance value
    let inline _integrity_ value = Attr.integrity value
    let inline _inputmode_ value = Attr.inputmode value
    let _ismap_ = Attr.ismap
    let inline _itemprop_ value = Attr.itemprop value
    let inline _keytype_ value = Attr.keytype value
    let inline _kind_ value = Attr.kind value
    let inline _label_ value = Attr.label value
    let inline _lang_ value = Attr.lang value
    let inline _loading_ value = Attr.loading value
    let inline _list_ value = Attr.list value
    let _loop_ = Attr.loop
    let inline _low_ value = Attr.low value
    let inline _max_ value = Attr.max value
    let inline _maxlength_ value = Attr.maxlength value
    let inline _minlength_ value = Attr.minlength value
    let inline _media_ value = Attr.media value
    let inline _method_ value = Attr.method value
    let inline _min_ value = Attr.min value
    let _multiple_ = Attr.multiple
    let _muted_ = Attr.muted
    let inline _name_ value = Attr.name value
    let _novalidate_ = Attr.novalidate
    let inline _open_ value = Attr.open' value
    let inline _optimum_ value = Attr.optimum value
    let inline _pattern_ value = Attr.pattern value
    let inline _ping_ value = Attr.ping value
    let inline _placeholder_ value = Attr.placeholder value
    let inline _poster_ value = Attr.poster value
    let inline _preload_ value = Attr.preload value
    let inline _radiogroup_ value = Attr.radiogroup value
    let _readonly_ = Attr.readonly
    let inline _referrerpolicy_ value = Attr.referrerpolicy value
    let inline _rel_ value = Attr.rel value
    let _required_ = Attr.required
    let _reversed_ = Attr.reversed
    let inline _role_ value = Attr.role value
    let inline _rows_ value = Attr.rows value
    let inline _rowspan_ value = Attr.rowspan value
    let inline _sandbox_ value = Attr.sandbox value
    let inline _scope_ value = Attr.scope value
    let _selected_ = Attr.selected
    let inline _shape_ value = Attr.shape value
    let inline _size_ value = Attr.size value
    let inline _sizes_ value = Attr.sizes value
    let inline _slot_ value = Attr.slot value
    let inline _span_ value = Attr.span value
    let inline _spellcheck_ value = Attr.spellcheck value
    let inline _src_ value = Attr.src value
    let inline _srcdoc_ value = Attr.srcdoc value
    let inline _srclang_ value = Attr.srclang value
    let inline _srcset_ value = Attr.srcset value
    let inline _start_ value = Attr.start value
    let inline _step_ value = Attr.step value
    let inline _style_ value = Attr.style value
    let inline _tabindex_ value = Attr.tabindex value
    let inline _target_ value = Attr.target value
    let inline _title_ value = Attr.title value
    let inline _translate_ value = Attr.translate value
    let inline _type_ value = Attr.type' value
    let inline _usemap_ value = Attr.usemap value
    let inline _value_ value = Attr.value value
    let inline _width_ value = Attr.width value
    let inline _wrap_ value = Attr.wrap value
    let _enctypeForm_ = Attr.enctypeForm
    let _enctypeMultipart_ = Attr.enctypeMultipart
    let _methodPost_ = Attr.methodPost
    let _methodGet_ = Attr.methodGet
    let _methodDialog_ = Attr.methodDialog
    let _targetSelf_ = Attr.targetSelf
    let _targetBlank_ = Attr.targetBlank
    let _targetParent_ = Attr.targetParent
    let _targetTop_ = Attr.targetTop
    let _targetUnfencedTop_ = Attr.targetUnfencedTop
    let _typeButton_ = Attr.typeButton
    let _typeCheckbox_ = Attr.typeCheckbox
    let _typeColor_ = Attr.typeColor
    let _typeDate_ = Attr.typeDate
    let _typeDatetimeLocal_ = Attr.typeDatetimeLocal
    let _typeEmail_ = Attr.typeEmail
    let _typeFile_ = Attr.typeFile
    let _typeHidden_ = Attr.typeHidden
    let _typeImage_ = Attr.typeImage
    let _typeMonth_ = Attr.typeMonth
    let _typeNumber_ = Attr.typeNumber
    let _typePassword_ = Attr.typePassword
    let _typeRadio_ = Attr.typeRadio
    let _typeRange_ = Attr.typeRange
    let _typeReset_ = Attr.typeReset
    let _typeSearch_ = Attr.typeSearch
    let _typeSubmit_ = Attr.typeSubmit
    let _typeTel_ = Attr.typeTel
    let _typeText_ = Attr.typeText
    let _typeTime_ = Attr.typeTime
    let _typeUrl_ = Attr.typeUrl
    let _typeWeek_ = Attr.typeWeek
    let inline _onabort_ value = Attr.onabort value
    let inline _onafterprint_ value = Attr.onafterprint value
    let inline _onanimationend_ value = Attr.onanimationend value
    let inline _onanimationiteration_ value = Attr.onanimationiteration value
    let inline _onanimationstart_ value = Attr.onanimationstart value
    let inline _onbeforeprint_ value = Attr.onbeforeprint value
    let inline _onbeforeunload_ value = Attr.onbeforeunload value
    let inline _onblur_ value = Attr.onblur value
    let inline _oncanplay_ value = Attr.oncanplay value
    let inline _oncanplaythrough_ value = Attr.oncanplaythrough value
    let inline _onchange_ value = Attr.onchange value
    let inline _onclick_ value = Attr.onclick value
    let inline _oncontextmenu_ value = Attr.oncontextmenu value
    let inline _oncopy_ value = Attr.oncopy value
    let inline _oncut_ value = Attr.oncut value
    let inline _ondblclick_ value = Attr.ondblclick value
    let inline _ondrag_ value = Attr.ondrag value
    let inline _ondragend_ value = Attr.ondragend value
    let inline _ondragenter_ value = Attr.ondragenter value
    let inline _ondragleave_ value = Attr.ondragleave value
    let inline _ondragover_ value = Attr.ondragover value
    let inline _ondragstart_ value = Attr.ondragstart value
    let inline _ondrop_ value = Attr.ondrop value
    let inline _ondurationchange_ value = Attr.ondurationchange value
    let inline _onemptied_ value = Attr.onemptied value
    let inline _onended_ value = Attr.onended value
    let inline _onerror_ value = Attr.onerror value
    let inline _onfocus_ value = Attr.onfocus value
    let inline _onformchange_ value = Attr.onformchange value
    let inline _onforminput_ value = Attr.onforminput value
    let inline _onfocusin_ value = Attr.onfocusin value
    let inline _onfocusout_ value = Attr.onfocusout value
    let inline _onfullscreenchange_ value = Attr.onfullscreenchange value
    let inline _onfullscreenerror_ value = Attr.onfullscreenerror value
    let inline _onhashchange_ value = Attr.onhashchange value
    let inline _oninput_ value = Attr.oninput value
    let inline _oninvalid_ value = Attr.oninvalid value
    let inline _onkeydown_ value = Attr.onkeydown value
    let inline _onkeypress_ value = Attr.onkeypress value
    let inline _onkeyup_ value = Attr.onkeyup value
    let inline _onload_ value = Attr.onload value
    let inline _onloadeddata_ value = Attr.onloadeddata value
    let inline _onloadedmetadata_ value = Attr.onloadedmetadata value
    let inline _onloadstart_ value = Attr.onloadstart value
    let inline _onmessage_ value = Attr.onmessage value
    let inline _onmousedown_ value = Attr.onmousedown value
    let inline _onmouseenter_ value = Attr.onmouseenter value
    let inline _onmouseleave_ value = Attr.onmouseleave value
    let inline _onmousemove_ value = Attr.onmousemove value
    let inline _onmouseover_ value = Attr.onmouseover value
    let inline _onmouseout_ value = Attr.onmouseout value
    let inline _onmouseup_ value = Attr.onmouseup value
    let inline _onmousewheel_ value = Attr.onmousewheel value
    let inline _onoffline_ value = Attr.onoffline value
    let inline _ononline_ value = Attr.ononline value
    let inline _onopen_ value = Attr.onopen value
    let inline _onpagehide_ value = Attr.onpagehide value
    let inline _onpageshow_ value = Attr.onpageshow value
    let inline _onpaste_ value = Attr.onpaste value
    let inline _onpause_ value = Attr.onpause value
    let inline _onplay_ value = Attr.onplay value
    let inline _onplaying_ value = Attr.onplaying value
    let inline _onpopstate_ value = Attr.onpopstate value
    let inline _onprogress_ value = Attr.onprogress value
    let inline _onratechange_ value = Attr.onratechange value
    let inline _onresize_ value = Attr.onresize value
    let inline _onreset_ value = Attr.onreset value
    let inline _onscroll_ value = Attr.onscroll value
    let inline _onsearch_ value = Attr.onsearch value
    let inline _onseeked_ value = Attr.onseeked value
    let inline _onseeking_ value = Attr.onseeking value
    let inline _onselect_ value = Attr.onselect value
    let inline _onshow_ value = Attr.onshow value
    let inline _onstalled_ value = Attr.onstalled value
    let inline _onstorage_ value = Attr.onstorage value
    let inline _onsubmit_ value = Attr.onsubmit value
    let inline _onsuspend_ value = Attr.onsuspend value
    let inline _ontimeupdate_ value = Attr.ontimeupdate value
    let inline _ontoggle_ value = Attr.ontoggle value
    let inline _ontouchcancel_ value = Attr.ontouchcancel value
    let inline _ontouchend_ value = Attr.ontouchend value
    let inline _ontouchmove_ value = Attr.ontouchmove value
    let inline _ontouchstart_ value = Attr.ontouchstart value
    let inline _ontransitionend_ value = Attr.ontransitionend value
    let inline _onunload_ value = Attr.onunload value
    let inline _onvolumechange_ value = Attr.onvolumechange value
    let inline _onwaiting_ value = Attr.onwaiting value
    let inline _onwheel_ value = Attr.onwheel value
