module Falco.Tests.Attr

open System
open Falco.Markup
open FsUnit.Xunit
open Xunit

[<Fact>]
let ``Attr.valueString should invoke ToString member with no parameters`` () =
    Attr.valueString 1 |> should equal <| Attr.value "1"

[<Fact>]
let ``Attr.valueStringf should invoke ToString member with format parameter`` () =
    Attr.valueStringf "F2" 1.2345 |> should equal <| Attr.value "1.23"

[<Fact>]
let ``Attr.value{Type} should produce expected string`` () =
    let dt = (DateTime(1986,12,12,5,30,0))
    Attr.valueDate dt |> should equal <| Attr.value "1986-12-12"
    Attr.valueDatetimeLocal dt |> should equal <| Attr.value "1986-12-12T05:30:00"
    Attr.valueMonth dt |> should equal <| Attr.value "1986-12"
    Attr.valueTime (TimeSpan(12,12,0)) |> should equal <| Attr.value "12:12"
    Attr.valueWeek dt |> should equal <| Attr.value "1986-W50"

[<Fact>]
let ``Attr.valueOption + Attr.value{Type} should produce expected attribute`` () =
    let dt = Some (DateTime(1986,12,12,5,30,0))
    Attr.valueOption Attr.valueDate dt |> should equal <| Attr.value "1986-12-12"
    Attr.valueOption Attr.valueDatetimeLocal dt |> should equal <| Attr.value "1986-12-12T05:30:00"
    Attr.valueOption Attr.valueDate None |> should equal <| Attr.valueEmpty
    Attr.valueOption Attr.valueDatetimeLocal None |> should equal <| Attr.valueEmpty


[<Fact>]
let ``Attr.merge should combine two XmlAttribute lists`` () =
    Attr.merge
        [ _class_ "ma2"; _id_ "el" ]
        [ _id_ "some-el"; _class_ "bg-red"; _readonly_ ]
    |> should equal [ _class_ "ma2 bg-red"; _id_ "some-el"; _readonly_ ]

[<Fact>]
let ``Attr.merge should work with bogus "class" NonValueAttr`` () =
    Attr.merge
        [ _class_ "ma2" ]
        [ _id_ "some-el"; _class_ "bg-red"; NonValueAttr("class") ]
    |> should equal [ _class_ "ma2 bg-red"; _id_ "some-el" ]

[<Fact>]
let ``Attr.merge should combine two XmlAttribute lists factoring additive attributes`` () =
    Attr.merge
        [ _name_ "test"; _class_ "ma2"; _style_ "background: red"; _accept_ "image/jpeg" ]
        [ _name_ "expected"; _class_ "pa2"; _style_ "color: white"; _accept_ "image/png" ]
    |> should equal [ _name_ "expected"; _class_ "ma2 pa2"; _style_ "background: red; color: white"; _accept_ "image/jpeg, image/png" ]

[<Fact>]
let ``HTML Spec`` () =
    _div [ _accept_ "falco" ] [] |> renderNode |> should equal "<div accept=\"falco\"></div>"
    _div [ _acceptCharset_ "falco" ] [] |> renderNode |> should equal "<div accept-charset=\"falco\"></div>"
    _div [ _accesskey_ "falco" ] [] |> renderNode |> should equal "<div accesskey=\"falco\"></div>"
    _div [ _action_ "falco" ] [] |> renderNode |> should equal "<div action=\"falco\"></div>"
    _div [ _align_ "falco" ] [] |> renderNode |> should equal "<div align=\"falco\"></div>"
    _div [ _allow_ "falco" ] [] |> renderNode |> should equal "<div allow=\"falco\"></div>"
    _div [ _alt_ "falco" ] [] |> renderNode |> should equal "<div alt=\"falco\"></div>"
    _div [ _async_ ] [] |> renderNode |> should equal "<div async></div>"
    _div [ _autocapitalize_ "falco" ] [] |> renderNode |> should equal "<div autocapitalize=\"falco\"></div>"
    _div [ _autocomplete_ "falco" ] [] |> renderNode |> should equal "<div autocomplete=\"falco\"></div>"
    _div [ _autofocus_ ] [] |> renderNode |> should equal "<div autofocus></div>"
    _div [ _autoplay_ ] [] |> renderNode |> should equal "<div autoplay></div>"
    _div [ _background_ "falco" ] [] |> renderNode |> should equal "<div background=\"falco\"></div>"
    _div [ _bgcolor_ "falco" ] [] |> renderNode |> should equal "<div bgcolor=\"falco\"></div>"
    _div [ _border_ "falco" ] [] |> renderNode |> should equal "<div border=\"falco\"></div>"
    _div [ _buffered_ "falco" ] [] |> renderNode |> should equal "<div buffered=\"falco\"></div>"
    _div [ _capture_ "falco" ] [] |> renderNode |> should equal "<div capture=\"falco\"></div>"
    _div [ _challenge_ "falco" ] [] |> renderNode |> should equal "<div challenge=\"falco\"></div>"
    _div [ _charset_ "falco" ] [] |> renderNode |> should equal "<div charset=\"falco\"></div>"
    _div [ _checked_ ] [] |> renderNode |> should equal "<div checked></div>"
    _div [ _cite_ "falco" ] [] |> renderNode |> should equal "<div cite=\"falco\"></div>"
    _div [ _class_ "falco" ] [] |> renderNode |> should equal "<div class=\"falco\"></div>"
    _div [ _code_ "falco" ] [] |> renderNode |> should equal "<div code=\"falco\"></div>"
    _div [ _codebase_ "falco" ] [] |> renderNode |> should equal "<div codebase=\"falco\"></div>"
    _div [ _color_ "falco" ] [] |> renderNode |> should equal "<div color=\"falco\"></div>"
    _div [ _cols_ "falco" ] [] |> renderNode |> should equal "<div cols=\"falco\"></div>"
    _div [ _colspan_ "falco" ] [] |> renderNode |> should equal "<div colspan=\"falco\"></div>"
    _div [ _content_ "falco" ] [] |> renderNode |> should equal "<div content=\"falco\"></div>"
    _div [ _contenteditable_ "falco" ] [] |> renderNode |> should equal "<div contenteditable=\"falco\"></div>"
    _div [ _contextmenu_ "falco" ] [] |> renderNode |> should equal "<div contextmenu=\"falco\"></div>"
    _div [ _controls_ ] [] |> renderNode |> should equal "<div controls></div>"
    _div [ _coords_ "falco" ] [] |> renderNode |> should equal "<div coords=\"falco\"></div>"
    _div [ _crossorigin_ "falco" ] [] |> renderNode |> should equal "<div crossorigin=\"falco\"></div>"
    _div [ _csp_ "falco" ] [] |> renderNode |> should equal "<div csp=\"falco\"></div>"
    _div [ _data_ "falco" ] [] |> renderNode |> should equal "<div data=\"falco\"></div>"
    _div [ _dataAttr_ "value" "falco" ] [] |> renderNode |> should equal "<div data-value=\"falco\"></div>"
    _div [ _datetime_ "falco" ] [] |> renderNode |> should equal "<div datetime=\"falco\"></div>"
    _div [ _decoding_ "falco" ] [] |> renderNode |> should equal "<div decoding=\"falco\"></div>"
    _div [ _default_ ] [] |> renderNode |> should equal "<div default></div>"
    _div [ _defer_ ] [] |> renderNode |> should equal "<div defer></div>"
    _div [ _dir_ "falco" ] [] |> renderNode |> should equal "<div dir=\"falco\"></div>"
    _div [ _dirname_ "falco" ] [] |> renderNode |> should equal "<div dirname=\"falco\"></div>"
    _div [ _disabled_ ] [] |> renderNode |> should equal "<div disabled></div>"
    _div [ _download_ "falco" ] [] |> renderNode |> should equal "<div download=\"falco\"></div>"
    _div [ _draggable_ "falco" ] [] |> renderNode |> should equal "<div draggable=\"falco\"></div>"
    _div [ _enctype_ "falco" ] [] |> renderNode |> should equal "<div enctype=\"falco\"></div>"
    _div [ _enterkeyhint_ "falco" ] [] |> renderNode |> should equal "<div enterkeyhint=\"falco\"></div>"
    _div [ _for_ "falco" ] [] |> renderNode |> should equal "<div for=\"falco\"></div>"
    _div [ _form_ "falco" ] [] |> renderNode |> should equal "<div form=\"falco\"></div>"
    _div [ _formaction_ "falco" ] [] |> renderNode |> should equal "<div formaction=\"falco\"></div>"
    _div [ _formenctype_ "falco" ] [] |> renderNode |> should equal "<div formenctype=\"falco\"></div>"
    _div [ _formmethod_ "falco" ] [] |> renderNode |> should equal "<div formmethod=\"falco\"></div>"
    _div [ _formnovalidate_ ] [] |> renderNode |> should equal "<div formnovalidate></div>"
    _div [ _formtarget_ "falco" ] [] |> renderNode |> should equal "<div formtarget=\"falco\"></div>"
    _div [ _headers_ "falco" ] [] |> renderNode |> should equal "<div headers=\"falco\"></div>"
    _div [ _height_ "falco" ] [] |> renderNode |> should equal "<div height=\"falco\"></div>"
    _div [ _hidden_ ] [] |> renderNode |> should equal "<div hidden></div>"
    _div [ _high_ "falco" ] [] |> renderNode |> should equal "<div high=\"falco\"></div>"
    _div [ _href_ "falco" ] [] |> renderNode |> should equal "<div href=\"falco\"></div>"
    _div [ _hreflang_ "falco" ] [] |> renderNode |> should equal "<div hreflang=\"falco\"></div>"
    _div [ _httpEquiv_ "falco" ] [] |> renderNode |> should equal "<div http-equiv=\"falco\"></div>"
    _div [ _icon_ "falco" ] [] |> renderNode |> should equal "<div icon=\"falco\"></div>"
    _div [ _id_ "falco" ] [] |> renderNode |> should equal "<div id=\"falco\"></div>"
    _div [ _importance_ "falco" ] [] |> renderNode |> should equal "<div importance=\"falco\"></div>"
    _div [ _integrity_ "falco" ] [] |> renderNode |> should equal "<div integrity=\"falco\"></div>"
    _div [ _inputmode_ "falco" ] [] |> renderNode |> should equal "<div inputmode=\"falco\"></div>"
    _div [ _ismap_ ] [] |> renderNode |> should equal "<div ismap></div>"
    _div [ _itemprop_ "falco" ] [] |> renderNode |> should equal "<div itemprop=\"falco\"></div>"
    _div [ _keytype_ "falco" ] [] |> renderNode |> should equal "<div keytype=\"falco\"></div>"
    _div [ _kind_ "falco" ] [] |> renderNode |> should equal "<div kind=\"falco\"></div>"
    _div [ _label_ "falco" ] [] |> renderNode |> should equal "<div label=\"falco\"></div>"
    _div [ _lang_ "falco" ] [] |> renderNode |> should equal "<div lang=\"falco\"></div>"
    _div [ _loading_ "falco" ] [] |> renderNode |> should equal "<div loading=\"falco\"></div>"
    _div [ _list_ "falco" ] [] |> renderNode |> should equal "<div list=\"falco\"></div>"
    _div [ _loop_ ] [] |> renderNode |> should equal "<div loop></div>"
    _div [ _low_ "falco" ] [] |> renderNode |> should equal "<div low=\"falco\"></div>"
    _div [ _max_ "falco" ] [] |> renderNode |> should equal "<div max=\"falco\"></div>"
    _div [ _maxlength_ "falco" ] [] |> renderNode |> should equal "<div maxlength=\"falco\"></div>"
    _div [ _minlength_ "falco" ] [] |> renderNode |> should equal "<div minlength=\"falco\"></div>"
    _div [ _media_ "falco" ] [] |> renderNode |> should equal "<div media=\"falco\"></div>"
    _div [ _method_ "falco" ] [] |> renderNode |> should equal "<div method=\"falco\"></div>"
    _div [ _min_ "falco" ] [] |> renderNode |> should equal "<div min=\"falco\"></div>"
    _div [ _multiple_ ] [] |> renderNode |> should equal "<div multiple></div>"
    _div [ _muted_ ] [] |> renderNode |> should equal "<div muted></div>"
    _div [ _name_ "falco" ] [] |> renderNode |> should equal "<div name=\"falco\"></div>"
    _div [ _novalidate_ ] [] |> renderNode |> should equal "<div novalidate></div>"
    _div [ _open_ "falco" ] [] |> renderNode |> should equal "<div open=\"falco\"></div>"
    _div [ _optimum_ "falco" ] [] |> renderNode |> should equal "<div optimum=\"falco\"></div>"
    _div [ _pattern_ "falco" ] [] |> renderNode |> should equal "<div pattern=\"falco\"></div>"
    _div [ _ping_ "falco" ] [] |> renderNode |> should equal "<div ping=\"falco\"></div>"
    _div [ _placeholder_ "falco" ] [] |> renderNode |> should equal "<div placeholder=\"falco\"></div>"
    _div [ _poster_ "falco" ] [] |> renderNode |> should equal "<div poster=\"falco\"></div>"
    _div [ _preload_ "falco" ] [] |> renderNode |> should equal "<div preload=\"falco\"></div>"
    _div [ _radiogroup_ "falco" ] [] |> renderNode |> should equal "<div radiogroup=\"falco\"></div>"
    _div [ _readonly_ ] [] |> renderNode |> should equal "<div readonly></div>"
    _div [ _referrerpolicy_ "falco" ] [] |> renderNode |> should equal "<div referrerpolicy=\"falco\"></div>"
    _div [ _rel_ "falco" ] [] |> renderNode |> should equal "<div rel=\"falco\"></div>"
    _div [ _required_ ] [] |> renderNode |> should equal "<div required></div>"
    _div [ _reversed_ ] [] |> renderNode |> should equal "<div reversed></div>"
    _div [ _role_ "falco" ] [] |> renderNode |> should equal "<div role=\"falco\"></div>"
    _div [ _rows_ "falco" ] [] |> renderNode |> should equal "<div rows=\"falco\"></div>"
    _div [ _rowspan_ "falco" ] [] |> renderNode |> should equal "<div rowspan=\"falco\"></div>"
    _div [ _sandbox_ "falco" ] [] |> renderNode |> should equal "<div sandbox=\"falco\"></div>"
    _div [ _scope_ "falco" ] [] |> renderNode |> should equal "<div scope=\"falco\"></div>"
    _div [ _selected_ ] [] |> renderNode |> should equal "<div selected></div>"
    _div [ _shape_ "falco" ] [] |> renderNode |> should equal "<div shape=\"falco\"></div>"
    _div [ _size_ "falco" ] [] |> renderNode |> should equal "<div size=\"falco\"></div>"
    _div [ _sizes_ "falco" ] [] |> renderNode |> should equal "<div sizes=\"falco\"></div>"
    _div [ _slot_ "falco" ] [] |> renderNode |> should equal "<div slot=\"falco\"></div>"
    _div [ _span_ "falco" ] [] |> renderNode |> should equal "<div span=\"falco\"></div>"
    _div [ _spellcheck_ "falco" ] [] |> renderNode |> should equal "<div spellcheck=\"falco\"></div>"
    _div [ _src_ "falco" ] [] |> renderNode |> should equal "<div src=\"falco\"></div>"
    _div [ _srcdoc_ "falco" ] [] |> renderNode |> should equal "<div srcdoc=\"falco\"></div>"
    _div [ _srclang_ "falco" ] [] |> renderNode |> should equal "<div srclang=\"falco\"></div>"
    _div [ _srcset_ "falco" ] [] |> renderNode |> should equal "<div srcset=\"falco\"></div>"
    _div [ _start_ "falco" ] [] |> renderNode |> should equal "<div start=\"falco\"></div>"
    _div [ _step_ "falco" ] [] |> renderNode |> should equal "<div step=\"falco\"></div>"
    _div [ _style_ "falco" ] [] |> renderNode |> should equal "<div style=\"falco\"></div>"
    _div [ _tabindex_ "falco" ] [] |> renderNode |> should equal "<div tabindex=\"falco\"></div>"
    _div [ _target_ "falco" ] [] |> renderNode |> should equal "<div target=\"falco\"></div>"
    _div [ _title_ "falco" ] [] |> renderNode |> should equal "<div title=\"falco\"></div>"
    _div [ _translate_ "falco" ] [] |> renderNode |> should equal "<div translate=\"falco\"></div>"
    _div [ _type_ "falco" ] [] |> renderNode |> should equal "<div type=\"falco\"></div>"
    _div [ _usemap_ "falco" ] [] |> renderNode |> should equal "<div usemap=\"falco\"></div>"
    _div [ _value_ "falco" ] [] |> renderNode |> should equal "<div value=\"falco\"></div>"
    _div [ _width_ "falco" ] [] |> renderNode |> should equal "<div width=\"falco\"></div>"
    _div [ _wrap_ "falco" ] [] |> renderNode |> should equal "<div wrap=\"falco\"></div>"
    _div [ _onabort_ "falco" ] [] |> renderNode |> should equal "<div onabort=\"falco\"></div>"
    _div [ _onafterprint_ "falco" ] [] |> renderNode |> should equal "<div afterprint=\"falco\"></div>"
    _div [ _onanimationend_ "falco" ] [] |> renderNode |> should equal "<div animationend=\"falco\"></div>"
    _div [ _onanimationiteration_ "falco" ] [] |> renderNode |> should equal "<div animationiteration=\"falco\"></div>"
    _div [ _onanimationstart_ "falco" ] [] |> renderNode |> should equal "<div animationstart=\"falco\"></div>"
    _div [ _onbeforeprint_ "falco" ] [] |> renderNode |> should equal "<div beforeprint=\"falco\"></div>"
    _div [ _onbeforeunload_ "falco" ] [] |> renderNode |> should equal "<div beforeunload=\"falco\"></div>"
    _div [ _onblur_ "falco" ] [] |> renderNode |> should equal "<div onblur=\"falco\"></div>"
    _div [ _oncanplay_ "falco" ] [] |> renderNode |> should equal "<div oncanplay=\"falco\"></div>"
    _div [ _oncanplaythrough_ "falco" ] [] |> renderNode |> should equal "<div oncanplaythrough=\"falco\"></div>"
    _div [ _onchange_ "falco" ] [] |> renderNode |> should equal "<div onchange=\"falco\"></div>"
    _div [ _onclick_ "falco" ] [] |> renderNode |> should equal "<div onclick=\"falco\"></div>"
    _div [ _oncontextmenu_ "falco" ] [] |> renderNode |> should equal "<div oncontextmenu=\"falco\"></div>"
    _div [ _oncopy_ "falco" ] [] |> renderNode |> should equal "<div copy=\"falco\"></div>"
    _div [ _oncut_ "falco" ] [] |> renderNode |> should equal "<div cut=\"falco\"></div>"
    _div [ _ondblclick_ "falco" ] [] |> renderNode |> should equal "<div ondblclick=\"falco\"></div>"
    _div [ _ondrag_ "falco" ] [] |> renderNode |> should equal "<div ondrag=\"falco\"></div>"
    _div [ _ondragend_ "falco" ] [] |> renderNode |> should equal "<div ondragend=\"falco\"></div>"
    _div [ _ondragenter_ "falco" ] [] |> renderNode |> should equal "<div ondragenter=\"falco\"></div>"
    _div [ _ondragleave_ "falco" ] [] |> renderNode |> should equal "<div ondragleave=\"falco\"></div>"
    _div [ _ondragover_ "falco" ] [] |> renderNode |> should equal "<div ondragover=\"falco\"></div>"
    _div [ _ondragstart_ "falco" ] [] |> renderNode |> should equal "<div ondragstart=\"falco\"></div>"
    _div [ _ondrop_ "falco" ] [] |> renderNode |> should equal "<div ondrop=\"falco\"></div>"
    _div [ _ondurationchange_ "falco" ] [] |> renderNode |> should equal "<div ondurationchange=\"falco\"></div>"
    _div [ _onemptied_ "falco" ] [] |> renderNode |> should equal "<div onemptied=\"falco\"></div>"
    _div [ _onended_ "falco" ] [] |> renderNode |> should equal "<div onended=\"falco\"></div>"
    _div [ _onerror_ "falco" ] [] |> renderNode |> should equal "<div onerror=\"falco\"></div>"
    _div [ _onfocus_ "falco" ] [] |> renderNode |> should equal "<div onfocus=\"falco\"></div>"
    _div [ _onformchange_ "falco" ] [] |> renderNode |> should equal "<div onformchange=\"falco\"></div>"
    _div [ _onforminput_ "falco" ] [] |> renderNode |> should equal "<div onforminput=\"falco\"></div>"
    _div [ _onfocusin_ "falco" ] [] |> renderNode |> should equal "<div focusin=\"falco\"></div>"
    _div [ _onfocusout_ "falco" ] [] |> renderNode |> should equal "<div focusout=\"falco\"></div>"
    _div [ _onfullscreenchange_ "falco" ] [] |> renderNode |> should equal "<div fullscreenchange=\"falco\"></div>"
    _div [ _onfullscreenerror_ "falco" ] [] |> renderNode |> should equal "<div fullscreenerror=\"falco\"></div>"
    _div [ _onhashchange_ "falco" ] [] |> renderNode |> should equal "<div hashchange=\"falco\"></div>"
    _div [ _oninput_ "falco" ] [] |> renderNode |> should equal "<div oninput=\"falco\"></div>"
    _div [ _oninvalid_ "falco" ] [] |> renderNode |> should equal "<div oninvalid=\"falco\"></div>"
    _div [ _onkeydown_ "falco" ] [] |> renderNode |> should equal "<div onkeydown=\"falco\"></div>"
    _div [ _onkeypress_ "falco" ] [] |> renderNode |> should equal "<div onkeypress=\"falco\"></div>"
    _div [ _onkeyup_ "falco" ] [] |> renderNode |> should equal "<div onkeyup=\"falco\"></div>"
    _div [ _onload_ "falco" ] [] |> renderNode |> should equal "<div onload=\"falco\"></div>"
    _div [ _onloadeddata_ "falco" ] [] |> renderNode |> should equal "<div onloadeddata=\"falco\"></div>"
    _div [ _onloadedmetadata_ "falco" ] [] |> renderNode |> should equal "<div onloadedmetadata=\"falco\"></div>"
    _div [ _onloadstart_ "falco" ] [] |> renderNode |> should equal "<div onloadstart=\"falco\"></div>"
    _div [ _onmessage_ "falco" ] [] |> renderNode |> should equal "<div message=\"falco\"></div>"
    _div [ _onmousedown_ "falco" ] [] |> renderNode |> should equal "<div onmousedown=\"falco\"></div>"
    _div [ _onmouseenter_ "falco" ] [] |> renderNode |> should equal "<div onmouseenter=\"falco\"></div>"
    _div [ _onmouseleave_ "falco" ] [] |> renderNode |> should equal "<div onmouseleave=\"falco\"></div>"
    _div [ _onmousemove_ "falco" ] [] |> renderNode |> should equal "<div onmousemove=\"falco\"></div>"
    _div [ _onmouseover_ "falco" ] [] |> renderNode |> should equal "<div onmouseover=\"falco\"></div>"
    _div [ _onmouseout_ "falco" ] [] |> renderNode |> should equal "<div onmouseout=\"falco\"></div>"
    _div [ _onmouseup_ "falco" ] [] |> renderNode |> should equal "<div onmouseup=\"falco\"></div>"
    _div [ _onmousewheel_ "falco" ] [] |> renderNode |> should equal "<div onmousewheel=\"falco\"></div>"
    _div [ _onoffline_ "falco" ] [] |> renderNode |> should equal "<div offline=\"falco\"></div>"
    _div [ _ononline_ "falco" ] [] |> renderNode |> should equal "<div online=\"falco\"></div>"
    _div [ _onopen_ "falco" ] [] |> renderNode |> should equal "<div open=\"falco\"></div>"
    _div [ _onpagehide_ "falco" ] [] |> renderNode |> should equal "<div pagehide=\"falco\"></div>"
    _div [ _onpageshow_ "falco" ] [] |> renderNode |> should equal "<div pageshow=\"falco\"></div>"
    _div [ _onpaste_ "falco" ] [] |> renderNode |> should equal "<div paste=\"falco\"></div>"
    _div [ _onpause_ "falco" ] [] |> renderNode |> should equal "<div onpause=\"falco\"></div>"
    _div [ _onplay_ "falco" ] [] |> renderNode |> should equal "<div onplay=\"falco\"></div>"
    _div [ _onplaying_ "falco" ] [] |> renderNode |> should equal "<div onplaying=\"falco\"></div>"
    _div [ _onpopstate_ "falco" ] [] |> renderNode |> should equal "<div popstate=\"falco\"></div>"
    _div [ _onprogress_ "falco" ] [] |> renderNode |> should equal "<div onprogress=\"falco\"></div>"
    _div [ _onratechange_ "falco" ] [] |> renderNode |> should equal "<div onratechange=\"falco\"></div>"
    _div [ _onresize_ "falco" ] [] |> renderNode |> should equal "<div onresize=\"falco\"></div>"
    _div [ _onreset_ "falco" ] [] |> renderNode |> should equal "<div onreset=\"falco\"></div>"
    _div [ _onscroll_ "falco" ] [] |> renderNode |> should equal "<div onscroll=\"falco\"></div>"
    _div [ _onsearch_ "falco" ] [] |> renderNode |> should equal "<div search=\"falco\"></div>"
    _div [ _onseeked_ "falco" ] [] |> renderNode |> should equal "<div onseeked=\"falco\"></div>"
    _div [ _onseeking_ "falco" ] [] |> renderNode |> should equal "<div onseeking=\"falco\"></div>"
    _div [ _onselect_ "falco" ] [] |> renderNode |> should equal "<div onselect=\"falco\"></div>"
    _div [ _onshow_ "falco" ] [] |> renderNode |> should equal "<div onshow=\"falco\"></div>"
    _div [ _onstalled_ "falco" ] [] |> renderNode |> should equal "<div onstalled=\"falco\"></div>"
    _div [ _onstorage_ "falco" ] [] |> renderNode |> should equal "<div storage=\"falco\"></div>"
    _div [ _onsubmit_ "falco" ] [] |> renderNode |> should equal "<div onsubmit=\"falco\"></div>"
    _div [ _onsuspend_ "falco" ] [] |> renderNode |> should equal "<div onsuspend=\"falco\"></div>"
    _div [ _ontimeupdate_ "falco" ] [] |> renderNode |> should equal "<div ontimeupdate=\"falco\"></div>"
    _div [ _ontoggle_ "falco" ] [] |> renderNode |> should equal "<div toggle=\"falco\"></div>"
    _div [ _ontouchcancel_ "falco" ] [] |> renderNode |> should equal "<div touchcancel=\"falco\"></div>"
    _div [ _ontouchend_ "falco" ] [] |> renderNode |> should equal "<div touchend=\"falco\"></div>"
    _div [ _ontouchmove_ "falco" ] [] |> renderNode |> should equal "<div touchmove=\"falco\"></div>"
    _div [ _ontouchstart_ "falco" ] [] |> renderNode |> should equal "<div touchstart=\"falco\"></div>"
    _div [ _ontransitionend_ "falco" ] [] |> renderNode |> should equal "<div transitionend=\"falco\"></div>"
    _div [ _onunload_ "falco" ] [] |> renderNode |> should equal "<div unload=\"falco\"></div>"
    _div [ _onvolumechange_ "falco" ] [] |> renderNode |> should equal "<div onvolumechange=\"falco\"></div>"
    _div [ _onwaiting_ "falco" ] [] |> renderNode |> should equal "<div onwaiting=\"falco\"></div>"
    _div [ _onwheel_ "falco" ] [] |> renderNode |> should equal "<div wheel=\"falco\"></div>"
