module Falco.Tests.Html

open Falco.Markup
open FsUnit.Xunit
open Xunit

[<Fact>]
let ``Elements`` () =
    _html [] [] |> should equal <| Elem.html [] []
    _base [] |> should equal <| Elem.base' []
    _head [] [] |> should equal <| Elem.head [] []
    _link [] |> should equal <| Elem.link []
    _meta [] |> should equal <| Elem.meta []
    _style [] [] |> should equal <| Elem.style [] []
    _title [] [] |> should equal <| Elem.title [] []
    _body [] [] |> should equal <| Elem.body [] []
    _address [] [] |> should equal <| Elem.address [] []
    _article [] [] |> should equal <| Elem.article [] []
    _aside [] [] |> should equal <| Elem.aside [] []
    _footer [] [] |> should equal <| Elem.footer [] []
    _header [] [] |> should equal <| Elem.header [] []
    _h1 [] [] |> should equal <| Elem.h1 [] []
    _h2 [] [] |> should equal <| Elem.h2 [] []
    _h3 [] [] |> should equal <| Elem.h3 [] []
    _h4 [] [] |> should equal <| Elem.h4 [] []
    _h5 [] [] |> should equal <| Elem.h5 [] []
    _h6 [] [] |> should equal <| Elem.h6 [] []
    _main [] [] |> should equal <| Elem.main [] []
    _nav [] [] |> should equal <| Elem.nav [] []
    _section [] [] |> should equal <| Elem.section [] []
    _blockquote [] [] |> should equal <| Elem.blockquote [] []
    _dd [] [] |> should equal <| Elem.dd [] []
    _div [] [] |> should equal <| Elem.div [] []
    _dl [] [] |> should equal <| Elem.dl [] []
    _dt [] [] |> should equal <| Elem.dt [] []
    _figcaption [] [] |> should equal <| Elem.figcaption [] []
    _figure [] [] |> should equal <| Elem.figure [] []
    _hr [] |> should equal <| Elem.hr []
    _li [] [] |> should equal <| Elem.li [] []
    _menu [] [] |> should equal <| Elem.menu [] []
    _ol [] [] |> should equal <| Elem.ol [] []
    _p [] [] |> should equal <| Elem.p [] []
    _pre [] [] |> should equal <| Elem.pre [] []
    _ul [] [] |> should equal <| Elem.ul [] []
    _a [] [] |> should equal <| Elem.a [] []
    _abbr [] [] |> should equal <| Elem.abbr [] []
    _b [] [] |> should equal <| Elem.b [] []
    _bdi [] [] |> should equal <| Elem.bdi [] []
    _bdo [] [] |> should equal <| Elem.bdo [] []
    _br [] |> should equal <| Elem.br []
    _cite [] [] |> should equal <| Elem.cite [] []
    _code [] [] |> should equal <| Elem.code [] []
    _data [] [] |> should equal <| Elem.data [] []
    _dfn [] [] |> should equal <| Elem.dfn [] []
    _em [] [] |> should equal <| Elem.em [] []
    _i [] [] |> should equal <| Elem.i [] []
    _kbd [] [] |> should equal <| Elem.kbd [] []
    _mark [] [] |> should equal <| Elem.mark [] []
    _q [] [] |> should equal <| Elem.q [] []
    _rp [] [] |> should equal <| Elem.rp [] []
    _rt [] [] |> should equal <| Elem.rt [] []
    _ruby [] [] |> should equal <| Elem.ruby [] []
    _s [] [] |> should equal <| Elem.s [] []
    _samp [] [] |> should equal <| Elem.samp [] []
    _small [] [] |> should equal <| Elem.small [] []
    _span [] [] |> should equal <| Elem.span [] []
    _strong [] [] |> should equal <| Elem.strong [] []
    _sub [] [] |> should equal <| Elem.sub [] []
    _sup [] [] |> should equal <| Elem.sup [] []
    _time [] [] |> should equal <| Elem.time [] []
    _u [] [] |> should equal <| Elem.u [] []
    _var [] [] |> should equal <| Elem.var [] []
    _wbr [] |> should equal <| Elem.wbr []
    _area [] [] |> should equal <| Elem.area [] []
    _audio [] [] |> should equal <| Elem.audio [] []
    _img [] |> should equal <| Elem.img []
    _map [] [] |> should equal <| Elem.map [] []
    _track [] |> should equal <| Elem.track []
    _video [] [] |> should equal <| Elem.video [] []
    _embed [] |> should equal <| Elem.embed []
    _iframe [] [] |> should equal <| Elem.iframe [] []
    _object [] [] |> should equal <| Elem.object [] []
    _picture [] [] |> should equal <| Elem.picture [] []
    _portal [] [] |> should equal <| Elem.portal [] []
    _source [] |> should equal <| Elem.source []
    _canvas [] [] |> should equal <| Elem.canvas [] []
    _noscript [] [] |> should equal <| Elem.noscript [] []
    _script [] [] |> should equal <| Elem.script [] []
    _del [] [] |> should equal <| Elem.del [] []
    _ins [] [] |> should equal <| Elem.ins [] []
    _caption [] [] |> should equal <| Elem.caption [] []
    _col [] |> should equal <| Elem.col []
    _colgroup [] [] |> should equal <| Elem.colgroup [] []
    _table [] [] |> should equal <| Elem.table [] []
    _tbody [] [] |> should equal <| Elem.tbody [] []
    _td [] [] |> should equal <| Elem.td [] []
    _tfoot [] [] |> should equal <| Elem.tfoot [] []
    _th [] [] |> should equal <| Elem.th [] []
    _thead [] [] |> should equal <| Elem.thead [] []
    _tr [] [] |> should equal <| Elem.tr [] []
    _button [] [] |> should equal <| Elem.button [] []
    _datalist [] [] |> should equal <| Elem.datalist [] []
    _fieldset [] [] |> should equal <| Elem.fieldset [] []
    _form [] [] |> should equal <| Elem.form [] []
    _input [] |> should equal <| Elem.input []
    _label [] [] |> should equal <| Elem.label [] []
    _legend [] [] |> should equal <| Elem.legend [] []
    _meter [] [] |> should equal <| Elem.meter [] []
    _optgroup [] [] |> should equal <| Elem.optgroup [] []
    _option [] [] |> should equal <| Elem.option [] []
    _output [] [] |> should equal <| Elem.output [] []
    _progress [] [] |> should equal <| Elem.progress [] []
    _select [] [] |> should equal <| Elem.select [] []
    _textarea [] [] |> should equal <| Elem.textarea [] []
    _details [] [] |> should equal <| Elem.details [] []
    _dialog [] [] |> should equal <| Elem.dialog [] []
    _summary [] [] |> should equal <| Elem.summary [] []
    _slot [] [] |> should equal <| Elem.slot [] []
    _template [] [] |> should equal <| Elem.template [] []
    _math [] [] |> should equal <| Elem.math [] []
    _svg [] [] |> should equal <| Elem.svg [] []

[<Fact>]
let ``Text`` () =
    h1_ "falco" |> should equal <| Text.h1 "falco"
    h2_ "falco" |> should equal <| Text.h2 "falco"
    h3_ "falco" |> should equal <| Text.h3 "falco"
    h4_ "falco" |> should equal <| Text.h4 "falco"
    h5_ "falco" |> should equal <| Text.h5 "falco"
    h6_ "falco" |> should equal <| Text.h6 "falco"
    p_ "falco" |> should equal <| Text.p "falco"
    dd_ "falco" |> should equal <| Text.dd "falco"
    dt_ "falco" |> should equal <| Text.dt "falco"
    abbr_ "falco" |> should equal <| Text.abbr "falco"
    b_ "falco" |> should equal <| Text.b "falco"
    bdi_ "falco" |> should equal <| Text.bdi "falco"
    bdo_ "falco" |> should equal <| Text.bdo "falco"
    cite_ "falco" |> should equal <| Text.cite "falco"
    code_ "falco" |> should equal <| Text.code "falco"
    data_ "falco" |> should equal <| Text.data "falco"
    dfn_ "falco" |> should equal <| Text.dfn "falco"
    em_ "falco" |> should equal <| Text.em "falco"
    i_ "falco" |> should equal <| Text.i "falco"
    kbd_ "falco" |> should equal <| Text.kbd "falco"
    mark_ "falco" |> should equal <| Text.mark "falco"
    q_ "falco" |> should equal <| Text.q "falco"
    rp_ "falco" |> should equal <| Text.rp "falco"
    rt_ "falco" |> should equal <| Text.rt "falco"
    ruby_ "falco" |> should equal <| Text.ruby "falco"
    s_ "falco" |> should equal <| Text.s "falco"
    samp_ "falco" |> should equal <| Text.samp "falco"
    small_ "falco" |> should equal <| Text.small "falco"
    span_ "falco" |> should equal <| Text.span "falco"
    strong_ "falco" |> should equal <| Text.strong "falco"
    sub_ "falco" |> should equal <| Text.sub "falco"
    sup_ "falco" |> should equal <| Text.sup "falco"
    time_ "falco" |> should equal <| Text.time "falco"
    u_ "falco" |> should equal <| Text.u "falco"
    var_ "falco" |> should equal <| Text.var "falco"

[<Fact>]
let ``Attributes`` () =
    _div [ __accept "falco" ] [] |> should equal <| _div [ Attr.accept "falco" ] []
    _div [ __acceptCharset "falco" ] [] |> should equal <| _div [ Attr.acceptCharset "falco" ] []
    _div [ __accesskey "falco" ] [] |> should equal <| _div [ Attr.accesskey "falco" ] []
    _div [ __action "falco" ] [] |> should equal <| _div [ Attr.action "falco" ] []
    _div [ __align "falco" ] [] |> should equal <| _div [ Attr.align "falco" ] []
    _div [ __allow "falco" ] [] |> should equal <| _div [ Attr.allow "falco" ] []
    _div [ __alt "falco" ] [] |> should equal <| _div [ Attr.alt "falco" ] []
    _div [ __async ] [] |> should equal <| _div [ Attr.async ] []
    _div [ __autocapitalize "falco" ] [] |> should equal <| _div [ Attr.autocapitalize "falco" ] []
    _div [ __autocomplete "falco" ] [] |> should equal <| _div [ Attr.autocomplete "falco" ] []
    _div [ __autofocus ] [] |> should equal <| _div [ Attr.autofocus ] []
    _div [ __autoplay ] [] |> should equal <| _div [ Attr.autoplay ] []
    _div [ __background "falco" ] [] |> should equal <| _div [ Attr.background "falco" ] []
    _div [ __bgcolor "falco" ] [] |> should equal <| _div [ Attr.bgcolor "falco" ] []
    _div [ __border "falco" ] [] |> should equal <| _div [ Attr.border "falco" ] []
    _div [ __buffered "falco" ] [] |> should equal <| _div [ Attr.buffered "falco" ] []
    _div [ __capture "falco" ] [] |> should equal <| _div [ Attr.capture "falco" ] []
    _div [ __challenge "falco" ] [] |> should equal <| _div [ Attr.challenge "falco" ] []
    _div [ __charset "falco" ] [] |> should equal <| _div [ Attr.charset "falco" ] []
    _div [ __checked  ] [] |> should equal <| _div [ Attr.checked' ] []
    _div [ __cite "falco" ] [] |> should equal <| _div [ Attr.cite "falco" ] []
    _div [ __class "falco" ] [] |> should equal <| _div [ Attr.class' "falco" ] []
    _div [ __code "falco" ] [] |> should equal <| _div [ Attr.code "falco" ] []
    _div [ __codebase "falco" ] [] |> should equal <| _div [ Attr.codebase "falco" ] []
    _div [ __color "falco" ] [] |> should equal <| _div [ Attr.color "falco" ] []
    _div [ __cols "falco" ] [] |> should equal <| _div [ Attr.cols "falco" ] []
    _div [ __colspan "falco" ] [] |> should equal <| _div [ Attr.colspan "falco" ] []
    _div [ __content "falco" ] [] |> should equal <| _div [ Attr.content "falco" ] []
    _div [ __contenteditable "falco" ] [] |> should equal <| _div [ Attr.contenteditable "falco" ] []
    _div [ __contextmenu "falco" ] [] |> should equal <| _div [ Attr.contextmenu "falco" ] []
    _div [ __controls ] [] |> should equal <| _div [ Attr.controls ] []
    _div [ __coords "falco" ] [] |> should equal <| _div [ Attr.coords "falco" ] []
    _div [ __crossorigin "falco" ] [] |> should equal <| _div [ Attr.crossorigin "falco" ] []
    _div [ __csp "falco" ] [] |> should equal <| _div [ Attr.csp "falco" ] []
    _div [ __data "falco" ] [] |> should equal <| _div [ Attr.data "falco" ] []
    _div [ __dataAttr "value" "falco" ] [] |> should equal <| _div [ Attr.dataAttr "value" "falco" ] []
    _div [ __datetime "falco" ] [] |> should equal <| _div [ Attr.datetime "falco" ] []
    _div [ __decoding "falco" ] [] |> should equal <| _div [ Attr.decoding "falco" ] []
    _div [ __default  ] [] |> should equal <| _div [ Attr.default' ] []
    _div [ __defer ] [] |> should equal <| _div [ Attr.defer ] []
    _div [ __dir "falco" ] [] |> should equal <| _div [ Attr.dir "falco" ] []
    _div [ __dirname "falco" ] [] |> should equal <| _div [ Attr.dirname "falco" ] []
    _div [ __disabled ] [] |> should equal <| _div [ Attr.disabled ] []
    _div [ __download "falco" ] [] |> should equal <| _div [ Attr.download "falco" ] []
    _div [ __draggable "falco" ] [] |> should equal <| _div [ Attr.draggable "falco" ] []
    _div [ __enctype "falco" ] [] |> should equal <| _div [ Attr.enctype "falco" ] []
    _div [ __enterkeyhint "falco" ] [] |> should equal <| _div [ Attr.enterkeyhint "falco" ] []
    _div [ __for "falco" ] [] |> should equal <| _div [ Attr.for' "falco" ] []
    _div [ __form "falco" ] [] |> should equal <| _div [ Attr.form "falco" ] []
    _div [ __formaction "falco" ] [] |> should equal <| _div [ Attr.formaction "falco" ] []
    _div [ __formenctype "falco" ] [] |> should equal <| _div [ Attr.formenctype "falco" ] []
    _div [ __formmethod "falco" ] [] |> should equal <| _div [ Attr.formmethod "falco" ] []
    _div [ __formnovalidate ] [] |> should equal <| _div [ Attr.formnovalidate ] []
    _div [ __formtarget "falco" ] [] |> should equal <| _div [ Attr.formtarget "falco" ] []
    _div [ __headers "falco" ] [] |> should equal <| _div [ Attr.headers "falco" ] []
    _div [ __height "falco" ] [] |> should equal <| _div [ Attr.height "falco" ] []
    _div [ __hidden ] [] |> should equal <| _div [ Attr.hidden ] []
    _div [ __high "falco" ] [] |> should equal <| _div [ Attr.high "falco" ] []
    _div [ __href "falco" ] [] |> should equal <| _div [ Attr.href "falco" ] []
    _div [ __hreflang "falco" ] [] |> should equal <| _div [ Attr.hreflang "falco" ] []
    _div [ __httpEquiv "falco" ] [] |> should equal <| _div [ Attr.httpEquiv "falco" ] []
    _div [ __icon "falco" ] [] |> should equal <| _div [ Attr.icon "falco" ] []
    _div [ __id "falco" ] [] |> should equal <| _div [ Attr.id "falco" ] []
    _div [ __importance "falco" ] [] |> should equal <| _div [ Attr.importance "falco" ] []
    _div [ __integrity "falco" ] [] |> should equal <| _div [ Attr.integrity "falco" ] []
    _div [ __inputmode "falco" ] [] |> should equal <| _div [ Attr.inputmode "falco" ] []
    _div [ __ismap ] [] |> should equal <| _div [ Attr.ismap ] []
    _div [ __itemprop "falco" ] [] |> should equal <| _div [ Attr.itemprop "falco" ] []
    _div [ __keytype "falco" ] [] |> should equal <| _div [ Attr.keytype "falco" ] []
    _div [ __kind "falco" ] [] |> should equal <| _div [ Attr.kind "falco" ] []
    _div [ __label "falco" ] [] |> should equal <| _div [ Attr.label "falco" ] []
    _div [ __lang "falco" ] [] |> should equal <| _div [ Attr.lang "falco" ] []
    _div [ __loading "falco" ] [] |> should equal <| _div [ Attr.loading "falco" ] []
    _div [ __list "falco" ] [] |> should equal <| _div [ Attr.list "falco" ] []
    _div [ __loop ] [] |> should equal <| _div [ Attr.loop ] []
    _div [ __low "falco" ] [] |> should equal <| _div [ Attr.low "falco" ] []
    _div [ __max "falco" ] [] |> should equal <| _div [ Attr.max "falco" ] []
    _div [ __maxlength "falco" ] [] |> should equal <| _div [ Attr.maxlength "falco" ] []
    _div [ __minlength "falco" ] [] |> should equal <| _div [ Attr.minlength "falco" ] []
    _div [ __media "falco" ] [] |> should equal <| _div [ Attr.media "falco" ] []
    _div [ __method "falco" ] [] |> should equal <| _div [ Attr.method "falco" ] []
    _div [ __min "falco" ] [] |> should equal <| _div [ Attr.min "falco" ] []
    _div [ __multiple ] [] |> should equal <| _div [ Attr.multiple ] []
    _div [ __muted ] [] |> should equal <| _div [ Attr.muted ] []
    _div [ __name "falco" ] [] |> should equal <| _div [ Attr.name "falco" ] []
    _div [ __novalidate ] [] |> should equal <| _div [ Attr.novalidate ] []
    _div [ __open "falco" ] [] |> should equal <| _div [ Attr.open' "falco" ] []
    _div [ __optimum "falco" ] [] |> should equal <| _div [ Attr.optimum "falco" ] []
    _div [ __pattern "falco" ] [] |> should equal <| _div [ Attr.pattern "falco" ] []
    _div [ __ping "falco" ] [] |> should equal <| _div [ Attr.ping "falco" ] []
    _div [ __placeholder "falco" ] [] |> should equal <| _div [ Attr.placeholder "falco" ] []
    _div [ __poster "falco" ] [] |> should equal <| _div [ Attr.poster "falco" ] []
    _div [ __preload "falco" ] [] |> should equal <| _div [ Attr.preload "falco" ] []
    _div [ __radiogroup "falco" ] [] |> should equal <| _div [ Attr.radiogroup "falco" ] []
    _div [ __readonly ] [] |> should equal <| _div [ Attr.readonly ] []
    _div [ __referrerpolicy "falco" ] [] |> should equal <| _div [ Attr.referrerpolicy "falco" ] []
    _div [ __rel "falco" ] [] |> should equal <| _div [ Attr.rel "falco" ] []
    _div [ __required ] [] |> should equal <| _div [ Attr.required ] []
    _div [ __reversed ] [] |> should equal <| _div [ Attr.reversed ] []
    _div [ __role "falco" ] [] |> should equal <| _div [ Attr.role "falco" ] []
    _div [ __rows "falco" ] [] |> should equal <| _div [ Attr.rows "falco" ] []
    _div [ __rowspan "falco" ] [] |> should equal <| _div [ Attr.rowspan "falco" ] []
    _div [ __sandbox "falco" ] [] |> should equal <| _div [ Attr.sandbox "falco" ] []
    _div [ __scope "falco" ] [] |> should equal <| _div [ Attr.scope "falco" ] []
    _div [ __selected ] [] |> should equal <| _div [ Attr.selected ] []
    _div [ __shape "falco" ] [] |> should equal <| _div [ Attr.shape "falco" ] []
    _div [ __size "falco" ] [] |> should equal <| _div [ Attr.size "falco" ] []
    _div [ __sizes "falco" ] [] |> should equal <| _div [ Attr.sizes "falco" ] []
    _div [ __slot "falco" ] [] |> should equal <| _div [ Attr.slot "falco" ] []
    _div [ __span "falco" ] [] |> should equal <| _div [ Attr.span "falco" ] []
    _div [ __spellcheck "falco" ] [] |> should equal <| _div [ Attr.spellcheck "falco" ] []
    _div [ __src "falco" ] [] |> should equal <| _div [ Attr.src "falco" ] []
    _div [ __srcdoc "falco" ] [] |> should equal <| _div [ Attr.srcdoc "falco" ] []
    _div [ __srclang "falco" ] [] |> should equal <| _div [ Attr.srclang "falco" ] []
    _div [ __srcset "falco" ] [] |> should equal <| _div [ Attr.srcset "falco" ] []
    _div [ __start "falco" ] [] |> should equal <| _div [ Attr.start "falco" ] []
    _div [ __step "falco" ] [] |> should equal <| _div [ Attr.step "falco" ] []
    _div [ __style "falco" ] [] |> should equal <| _div [ Attr.style "falco" ] []
    _div [ __tabindex "falco" ] [] |> should equal <| _div [ Attr.tabindex "falco" ] []
    _div [ __target "falco" ] [] |> should equal <| _div [ Attr.target "falco" ] []
    _div [ __title "falco" ] [] |> should equal <| _div [ Attr.title "falco" ] []
    _div [ __translate "falco" ] [] |> should equal <| _div [ Attr.translate "falco" ] []
    _div [ __type "falco" ] [] |> should equal <| _div [ Attr.type' "falco" ] []
    _div [ __usemap "falco" ] [] |> should equal <| _div [ Attr.usemap "falco" ] []
    _div [ __value "falco" ] [] |> should equal <| _div [ Attr.value "falco" ] []
    _div [ __width "falco" ] [] |> should equal <| _div [ Attr.width "falco" ] []
    _div [ __wrap "falco" ] [] |> should equal <| _div [ Attr.wrap "falco" ] []
    _div [ __onabort "falco" ] [] |> should equal <| _div [ Attr.onabort "falco" ] []
    _div [ __onafterprint "falco" ] [] |> should equal <| _div [ Attr.onafterprint "falco" ] []
    _div [ __onanimationend "falco" ] [] |> should equal <| _div [ Attr.onanimationend "falco" ] []
    _div [ __onanimationiteration "falco" ] [] |> should equal <| _div [ Attr.onanimationiteration "falco" ] []
    _div [ __onanimationstart "falco" ] [] |> should equal <| _div [ Attr.onanimationstart "falco" ] []
    _div [ __onbeforeprint "falco" ] [] |> should equal <| _div [ Attr.onbeforeprint "falco" ] []
    _div [ __onbeforeunload "falco" ] [] |> should equal <| _div [ Attr.onbeforeunload "falco" ] []
    _div [ __onblur "falco" ] [] |> should equal <| _div [ Attr.onblur "falco" ] []
    _div [ __oncanplay "falco" ] [] |> should equal <| _div [ Attr.oncanplay "falco" ] []
    _div [ __oncanplaythrough "falco" ] [] |> should equal <| _div [ Attr.oncanplaythrough "falco" ] []
    _div [ __onchange "falco" ] [] |> should equal <| _div [ Attr.onchange "falco" ] []
    _div [ __onclick "falco" ] [] |> should equal <| _div [ Attr.onclick "falco" ] []
    _div [ __oncontextmenu "falco" ] [] |> should equal <| _div [ Attr.oncontextmenu "falco" ] []
    _div [ __oncopy "falco" ] [] |> should equal <| _div [ Attr.oncopy "falco" ] []
    _div [ __oncut "falco" ] [] |> should equal <| _div [ Attr.oncut "falco" ] []
    _div [ __ondblclick "falco" ] [] |> should equal <| _div [ Attr.ondblclick "falco" ] []
    _div [ __ondrag "falco" ] [] |> should equal <| _div [ Attr.ondrag "falco" ] []
    _div [ __ondragend "falco" ] [] |> should equal <| _div [ Attr.ondragend "falco" ] []
    _div [ __ondragenter "falco" ] [] |> should equal <| _div [ Attr.ondragenter "falco" ] []
    _div [ __ondragleave "falco" ] [] |> should equal <| _div [ Attr.ondragleave "falco" ] []
    _div [ __ondragover "falco" ] [] |> should equal <| _div [ Attr.ondragover "falco" ] []
    _div [ __ondragstart "falco" ] [] |> should equal <| _div [ Attr.ondragstart "falco" ] []
    _div [ __ondrop "falco" ] [] |> should equal <| _div [ Attr.ondrop "falco" ] []
    _div [ __ondurationchange "falco" ] [] |> should equal <| _div [ Attr.ondurationchange "falco" ] []
    _div [ __onemptied "falco" ] [] |> should equal <| _div [ Attr.onemptied "falco" ] []
    _div [ __onended "falco" ] [] |> should equal <| _div [ Attr.onended "falco" ] []
    _div [ __onerror "falco" ] [] |> should equal <| _div [ Attr.onerror "falco" ] []
    _div [ __onfocus "falco" ] [] |> should equal <| _div [ Attr.onfocus "falco" ] []
    _div [ __onformchange "falco" ] [] |> should equal <| _div [ Attr.onformchange "falco" ] []
    _div [ __onforminput "falco" ] [] |> should equal <| _div [ Attr.onforminput "falco" ] []
    _div [ __onfocusin "falco" ] [] |> should equal <| _div [ Attr.onfocusin "falco" ] []
    _div [ __onfocusout "falco" ] [] |> should equal <| _div [ Attr.onfocusout "falco" ] []
    _div [ __onfullscreenchange "falco" ] [] |> should equal <| _div [ Attr.onfullscreenchange "falco" ] []
    _div [ __onfullscreenerror "falco" ] [] |> should equal <| _div [ Attr.onfullscreenerror "falco" ] []
    _div [ __onhashchange "falco" ] [] |> should equal <| _div [ Attr.onhashchange "falco" ] []
    _div [ __oninput "falco" ] [] |> should equal <| _div [ Attr.oninput "falco" ] []
    _div [ __oninvalid "falco" ] [] |> should equal <| _div [ Attr.oninvalid "falco" ] []
    _div [ __onkeydown "falco" ] [] |> should equal <| _div [ Attr.onkeydown "falco" ] []
    _div [ __onkeypress "falco" ] [] |> should equal <| _div [ Attr.onkeypress "falco" ] []
    _div [ __onkeyup "falco" ] [] |> should equal <| _div [ Attr.onkeyup "falco" ] []
    _div [ __onload "falco" ] [] |> should equal <| _div [ Attr.onload "falco" ] []
    _div [ __onloadeddata "falco" ] [] |> should equal <| _div [ Attr.onloadeddata "falco" ] []
    _div [ __onloadedmetadata "falco" ] [] |> should equal <| _div [ Attr.onloadedmetadata "falco" ] []
    _div [ __onloadstart "falco" ] [] |> should equal <| _div [ Attr.onloadstart "falco" ] []
    _div [ __onmessage "falco" ] [] |> should equal <| _div [ Attr.onmessage "falco" ] []
    _div [ __onmousedown "falco" ] [] |> should equal <| _div [ Attr.onmousedown "falco" ] []
    _div [ __onmouseenter "falco" ] [] |> should equal <| _div [ Attr.onmouseenter "falco" ] []
    _div [ __onmouseleave "falco" ] [] |> should equal <| _div [ Attr.onmouseleave "falco" ] []
    _div [ __onmousemove "falco" ] [] |> should equal <| _div [ Attr.onmousemove "falco" ] []
    _div [ __onmouseover "falco" ] [] |> should equal <| _div [ Attr.onmouseover "falco" ] []
    _div [ __onmouseout "falco" ] [] |> should equal <| _div [ Attr.onmouseout "falco" ] []
    _div [ __onmouseup "falco" ] [] |> should equal <| _div [ Attr.onmouseup "falco" ] []
    _div [ __onmousewheel "falco" ] [] |> should equal <| _div [ Attr.onmousewheel "falco" ] []
    _div [ __onoffline "falco" ] [] |> should equal <| _div [ Attr.onoffline "falco" ] []
    _div [ __ononline "falco" ] [] |> should equal <| _div [ Attr.ononline "falco" ] []
    _div [ __onopen "falco" ] [] |> should equal <| _div [ Attr.onopen "falco" ] []
    _div [ __onpagehide "falco" ] [] |> should equal <| _div [ Attr.onpagehide "falco" ] []
    _div [ __onpageshow "falco" ] [] |> should equal <| _div [ Attr.onpageshow "falco" ] []
    _div [ __onpaste "falco" ] [] |> should equal <| _div [ Attr.onpaste "falco" ] []
    _div [ __onpause "falco" ] [] |> should equal <| _div [ Attr.onpause "falco" ] []
    _div [ __onplay "falco" ] [] |> should equal <| _div [ Attr.onplay "falco" ] []
    _div [ __onplaying "falco" ] [] |> should equal <| _div [ Attr.onplaying "falco" ] []
    _div [ __onpopstate "falco" ] [] |> should equal <| _div [ Attr.onpopstate "falco" ] []
    _div [ __onprogress "falco" ] [] |> should equal <| _div [ Attr.onprogress "falco" ] []
    _div [ __onratechange "falco" ] [] |> should equal <| _div [ Attr.onratechange "falco" ] []
    _div [ __onresize "falco" ] [] |> should equal <| _div [ Attr.onresize "falco" ] []
    _div [ __onreset "falco" ] [] |> should equal <| _div [ Attr.onreset "falco" ] []
    _div [ __onscroll "falco" ] [] |> should equal <| _div [ Attr.onscroll "falco" ] []
    _div [ __onsearch "falco" ] [] |> should equal <| _div [ Attr.onsearch "falco" ] []
    _div [ __onseeked "falco" ] [] |> should equal <| _div [ Attr.onseeked "falco" ] []
    _div [ __onseeking "falco" ] [] |> should equal <| _div [ Attr.onseeking "falco" ] []
    _div [ __onselect "falco" ] [] |> should equal <| _div [ Attr.onselect "falco" ] []
    _div [ __onshow "falco" ] [] |> should equal <| _div [ Attr.onshow "falco" ] []
    _div [ __onstalled "falco" ] [] |> should equal <| _div [ Attr.onstalled "falco" ] []
    _div [ __onstorage "falco" ] [] |> should equal <| _div [ Attr.onstorage "falco" ] []
    _div [ __onsubmit "falco" ] [] |> should equal <| _div [ Attr.onsubmit "falco" ] []
    _div [ __onsuspend "falco" ] [] |> should equal <| _div [ Attr.onsuspend "falco" ] []
    _div [ __ontimeupdate "falco" ] [] |> should equal <| _div [ Attr.ontimeupdate "falco" ] []
    _div [ __ontoggle "falco" ] [] |> should equal <| _div [ Attr.ontoggle "falco" ] []
    _div [ __ontouchcancel "falco" ] [] |> should equal <| _div [ Attr.ontouchcancel "falco" ] []
    _div [ __ontouchend "falco" ] [] |> should equal <| _div [ Attr.ontouchend "falco" ] []
    _div [ __ontouchmove "falco" ] [] |> should equal <| _div [ Attr.ontouchmove "falco" ] []
    _div [ __ontouchstart "falco" ] [] |> should equal <| _div [ Attr.ontouchstart "falco" ] []
    _div [ __ontransitionend "falco" ] [] |> should equal <| _div [ Attr.ontransitionend "falco" ] []
    _div [ __onunload "falco" ] [] |> should equal <| _div [ Attr.onunload "falco" ] []
    _div [ __onvolumechange "falco" ] [] |> should equal <| _div [ Attr.onvolumechange "falco" ] []
    _div [ __onwaiting "falco" ] [] |> should equal <| _div [ Attr.onwaiting "falco" ] []
    _div [ __onwheel "falco" ] [] |> should equal <| _div [ Attr.onwheel "falco" ] []
