module Falco.Tests.Html

open Falco.Markup
open FsUnit.Xunit
open Xunit

[<Fact>]
let ``Elements`` () =
    _html [] [] |> should equal <| Elem.html [] []
    _base [] |> should equal <| Elem.base' []
    _head [] [] |> should equal <| Elem.head [] []
    _link [] |> should equal <| Elem.link []
    _meta [] |> should equal <| Elem.meta []
    _style [] [] |> should equal <| Elem.style [] []
    _title [] [] |> should equal <| Elem.title [] []
    _body [] [] |> should equal <| Elem.body [] []
    _address [] [] |> should equal <| Elem.address [] []
    _article [] [] |> should equal <| Elem.article [] []
    _aside [] [] |> should equal <| Elem.aside [] []
    _footer [] [] |> should equal <| Elem.footer [] []
    _header [] [] |> should equal <| Elem.header [] []
    _h1 [] [] |> should equal <| Elem.h1 [] []
    _h2 [] [] |> should equal <| Elem.h2 [] []
    _h3 [] [] |> should equal <| Elem.h3 [] []
    _h4 [] [] |> should equal <| Elem.h4 [] []
    _h5 [] [] |> should equal <| Elem.h5 [] []
    _h6 [] [] |> should equal <| Elem.h6 [] []
    _main [] [] |> should equal <| Elem.main [] []
    _nav [] [] |> should equal <| Elem.nav [] []
    _section [] [] |> should equal <| Elem.section [] []
    _blockquote [] [] |> should equal <| Elem.blockquote [] []
    _dd [] [] |> should equal <| Elem.dd [] []
    _div [] [] |> should equal <| Elem.div [] []
    _dl [] [] |> should equal <| Elem.dl [] []
    _dt [] [] |> should equal <| Elem.dt [] []
    _figcaption [] [] |> should equal <| Elem.figcaption [] []
    _figure [] [] |> should equal <| Elem.figure [] []
    _hr [] |> should equal <| Elem.hr []
    _li [] [] |> should equal <| Elem.li [] []
    _menu [] [] |> should equal <| Elem.menu [] []
    _ol [] [] |> should equal <| Elem.ol [] []
    _p [] [] |> should equal <| Elem.p [] []
    _pre [] [] |> should equal <| Elem.pre [] []
    _ul [] [] |> should equal <| Elem.ul [] []
    _a [] [] |> should equal <| Elem.a [] []
    _abbr [] [] |> should equal <| Elem.abbr [] []
    _b [] [] |> should equal <| Elem.b [] []
    _bdi [] [] |> should equal <| Elem.bdi [] []
    _bdo [] [] |> should equal <| Elem.bdo [] []
    _br [] |> should equal <| Elem.br []
    _cite [] [] |> should equal <| Elem.cite [] []
    _code [] [] |> should equal <| Elem.code [] []
    _data [] [] |> should equal <| Elem.data [] []
    _dfn [] [] |> should equal <| Elem.dfn [] []
    _em [] [] |> should equal <| Elem.em [] []
    _i [] [] |> should equal <| Elem.i [] []
    _kbd [] [] |> should equal <| Elem.kbd [] []
    _mark [] [] |> should equal <| Elem.mark [] []
    _q [] [] |> should equal <| Elem.q [] []
    _rp [] [] |> should equal <| Elem.rp [] []
    _rt [] [] |> should equal <| Elem.rt [] []
    _ruby [] [] |> should equal <| Elem.ruby [] []
    _s [] [] |> should equal <| Elem.s [] []
    _samp [] [] |> should equal <| Elem.samp [] []
    _small [] [] |> should equal <| Elem.small [] []
    _span [] [] |> should equal <| Elem.span [] []
    _strong [] [] |> should equal <| Elem.strong [] []
    _sub [] [] |> should equal <| Elem.sub [] []
    _sup [] [] |> should equal <| Elem.sup [] []
    _time [] [] |> should equal <| Elem.time [] []
    _u [] [] |> should equal <| Elem.u [] []
    _var [] [] |> should equal <| Elem.var [] []
    _wbr [] |> should equal <| Elem.wbr []
    _area [] [] |> should equal <| Elem.area [] []
    _audio [] [] |> should equal <| Elem.audio [] []
    _img [] |> should equal <| Elem.img []
    _map [] [] |> should equal <| Elem.map [] []
    _track [] |> should equal <| Elem.track []
    _video [] [] |> should equal <| Elem.video [] []
    _embed [] |> should equal <| Elem.embed []
    _iframe [] [] |> should equal <| Elem.iframe [] []
    _object [] [] |> should equal <| Elem.object [] []
    _picture [] [] |> should equal <| Elem.picture [] []
    _portal [] [] |> should equal <| Elem.portal [] []
    _source [] |> should equal <| Elem.source []
    _canvas [] [] |> should equal <| Elem.canvas [] []
    _noscript [] [] |> should equal <| Elem.noscript [] []
    _script [] [] |> should equal <| Elem.script [] []
    _del [] [] |> should equal <| Elem.del [] []
    _ins [] [] |> should equal <| Elem.ins [] []
    _caption [] [] |> should equal <| Elem.caption [] []
    _col [] |> should equal <| Elem.col []
    _colgroup [] [] |> should equal <| Elem.colgroup [] []
    _table [] [] |> should equal <| Elem.table [] []
    _tbody [] [] |> should equal <| Elem.tbody [] []
    _td [] [] |> should equal <| Elem.td [] []
    _tfoot [] [] |> should equal <| Elem.tfoot [] []
    _th [] [] |> should equal <| Elem.th [] []
    _thead [] [] |> should equal <| Elem.thead [] []
    _tr [] [] |> should equal <| Elem.tr [] []
    _button [] [] |> should equal <| Elem.button [] []
    _datalist [] [] |> should equal <| Elem.datalist [] []
    _fieldset [] [] |> should equal <| Elem.fieldset [] []
    _form [] [] |> should equal <| Elem.form [] []
    _input [] |> should equal <| Elem.input []
    _label [] [] |> should equal <| Elem.label [] []
    _legend [] [] |> should equal <| Elem.legend [] []
    _meter [] [] |> should equal <| Elem.meter [] []
    _optgroup [] [] |> should equal <| Elem.optgroup [] []
    _option [] [] |> should equal <| Elem.option [] []
    _output [] [] |> should equal <| Elem.output [] []
    _progress [] [] |> should equal <| Elem.progress [] []
    _select [] [] |> should equal <| Elem.select [] []
    _textarea [] [] |> should equal <| Elem.textarea [] []
    _details [] [] |> should equal <| Elem.details [] []
    _dialog [] [] |> should equal <| Elem.dialog [] []
    _summary [] [] |> should equal <| Elem.summary [] []
    _slot [] [] |> should equal <| Elem.slot [] []
    _template [] [] |> should equal <| Elem.template [] []
    _math [] [] |> should equal <| Elem.math [] []
    _svg [] [] |> should equal <| Elem.svg [] []

[<Fact>]
let ``Text`` () =
    _text "falco" |> should equal <| Text.raw "falco"
    _textf "falco %s" "rocks" |> should equal <| Text.rawf "falco %s" "rocks"
    _textEnc "falco" |> should equal <| Text.enc "falco"
    _h1' "falco" |> should equal <| Text.h1 "falco"
    _h2' "falco" |> should equal <| Text.h2 "falco"
    _h3' "falco" |> should equal <| Text.h3 "falco"
    _h4' "falco" |> should equal <| Text.h4 "falco"
    _h5' "falco" |> should equal <| Text.h5 "falco"
    _h6' "falco" |> should equal <| Text.h6 "falco"
    _p' "falco" |> should equal <| Text.p "falco"
    _dd' "falco" |> should equal <| Text.dd "falco"
    _dt' "falco" |> should equal <| Text.dt "falco"
    _abbr' "falco" |> should equal <| Text.abbr "falco"
    _b' "falco" |> should equal <| Text.b "falco"
    _bdi' "falco" |> should equal <| Text.bdi "falco"
    _bdo' "falco" |> should equal <| Text.bdo "falco"
    _cite' "falco" |> should equal <| Text.cite "falco"
    _code' "falco" |> should equal <| Text.code "falco"
    _data' "falco" |> should equal <| Text.data "falco"
    _dfn' "falco" |> should equal <| Text.dfn "falco"
    _em' "falco" |> should equal <| Text.em "falco"
    _i' "falco" |> should equal <| Text.i "falco"
    _kbd' "falco" |> should equal <| Text.kbd "falco"
    _mark' "falco" |> should equal <| Text.mark "falco"
    _q' "falco" |> should equal <| Text.q "falco"
    _rp' "falco" |> should equal <| Text.rp "falco"
    _rt' "falco" |> should equal <| Text.rt "falco"
    _ruby' "falco" |> should equal <| Text.ruby "falco"
    _s' "falco" |> should equal <| Text.s "falco"
    _samp' "falco" |> should equal <| Text.samp "falco"
    _small' "falco" |> should equal <| Text.small "falco"
    _span' "falco" |> should equal <| Text.span "falco"
    _strong' "falco" |> should equal <| Text.strong "falco"
    _sub' "falco" |> should equal <| Text.sub "falco"
    _sup' "falco" |> should equal <| Text.sup "falco"
    _time' "falco" |> should equal <| Text.time "falco"
    _u' "falco" |> should equal <| Text.u "falco"
    _var' "falco" |> should equal <| Text.var "falco"

[<Fact>]
let ``Attributes`` () =
    _div [ _accept_ "falco" ] [] |> should equal <| _div [ Attr.accept "falco" ] []
    _div [ _acceptCharset_ "falco" ] [] |> should equal <| _div [ Attr.acceptCharset "falco" ] []
    _div [ _accesskey_ "falco" ] [] |> should equal <| _div [ Attr.accesskey "falco" ] []
    _div [ _action_ "falco" ] [] |> should equal <| _div [ Attr.action "falco" ] []
    _div [ _align_ "falco" ] [] |> should equal <| _div [ Attr.align "falco" ] []
    _div [ _allow_ "falco" ] [] |> should equal <| _div [ Attr.allow "falco" ] []
    _div [ _alt_ "falco" ] [] |> should equal <| _div [ Attr.alt "falco" ] []
    _div [ _async_ ] [] |> should equal <| _div [ Attr.async ] []
    _div [ _autocapitalize_ "falco" ] [] |> should equal <| _div [ Attr.autocapitalize "falco" ] []
    _div [ _autocomplete_ "falco" ] [] |> should equal <| _div [ Attr.autocomplete "falco" ] []
    _div [ _autofocus_ ] [] |> should equal <| _div [ Attr.autofocus ] []
    _div [ _autoplay_ ] [] |> should equal <| _div [ Attr.autoplay ] []
    _div [ _background_ "falco" ] [] |> should equal <| _div [ Attr.background "falco" ] []
    _div [ _bgcolor_ "falco" ] [] |> should equal <| _div [ Attr.bgcolor "falco" ] []
    _div [ _border_ "falco" ] [] |> should equal <| _div [ Attr.border "falco" ] []
    _div [ _buffered_ "falco" ] [] |> should equal <| _div [ Attr.buffered "falco" ] []
    _div [ _capture_ "falco" ] [] |> should equal <| _div [ Attr.capture "falco" ] []
    _div [ _challenge_ "falco" ] [] |> should equal <| _div [ Attr.challenge "falco" ] []
    _div [ _charset_ "falco" ] [] |> should equal <| _div [ Attr.charset "falco" ] []
    _div [ _checked_  ] [] |> should equal <| _div [ Attr.checked' ] []
    _div [ _cite_ "falco" ] [] |> should equal <| _div [ Attr.cite "falco" ] []
    _div [ _class_ "falco" ] [] |> should equal <| _div [ Attr.class' "falco" ] []
    _div [ _code_ "falco" ] [] |> should equal <| _div [ Attr.code "falco" ] []
    _div [ _codebase_ "falco" ] [] |> should equal <| _div [ Attr.codebase "falco" ] []
    _div [ _color_ "falco" ] [] |> should equal <| _div [ Attr.color "falco" ] []
    _div [ _cols_ "falco" ] [] |> should equal <| _div [ Attr.cols "falco" ] []
    _div [ _colspan_ "falco" ] [] |> should equal <| _div [ Attr.colspan "falco" ] []
    _div [ _content_ "falco" ] [] |> should equal <| _div [ Attr.content "falco" ] []
    _div [ _contenteditable_ "falco" ] [] |> should equal <| _div [ Attr.contenteditable "falco" ] []
    _div [ _contextmenu_ "falco" ] [] |> should equal <| _div [ Attr.contextmenu "falco" ] []
    _div [ _controls_ ] [] |> should equal <| _div [ Attr.controls ] []
    _div [ _coords_ "falco" ] [] |> should equal <| _div [ Attr.coords "falco" ] []
    _div [ _crossorigin_ "falco" ] [] |> should equal <| _div [ Attr.crossorigin "falco" ] []
    _div [ _csp_ "falco" ] [] |> should equal <| _div [ Attr.csp "falco" ] []
    _div [ _data_ "falco" ] [] |> should equal <| _div [ Attr.data "falco" ] []
    _div [ _dataAttr_ "value" "falco" ] [] |> should equal <| _div [ Attr.dataAttr "value" "falco" ] []
    _div [ _datetime_ "falco" ] [] |> should equal <| _div [ Attr.datetime "falco" ] []
    _div [ _decoding_ "falco" ] [] |> should equal <| _div [ Attr.decoding "falco" ] []
    _div [ _default_  ] [] |> should equal <| _div [ Attr.default' ] []
    _div [ _defer_ ] [] |> should equal <| _div [ Attr.defer ] []
    _div [ _dir_ "falco" ] [] |> should equal <| _div [ Attr.dir "falco" ] []
    _div [ _dirname_ "falco" ] [] |> should equal <| _div [ Attr.dirname "falco" ] []
    _div [ _disabled_ ] [] |> should equal <| _div [ Attr.disabled ] []
    _div [ _download_ "falco" ] [] |> should equal <| _div [ Attr.download "falco" ] []
    _div [ _draggable_ "falco" ] [] |> should equal <| _div [ Attr.draggable "falco" ] []
    _div [ _enctype_ "falco" ] [] |> should equal <| _div [ Attr.enctype "falco" ] []
    _div [ _enterkeyhint_ "falco" ] [] |> should equal <| _div [ Attr.enterkeyhint "falco" ] []
    _div [ _for_ "falco" ] [] |> should equal <| _div [ Attr.for' "falco" ] []
    _div [ _form_ "falco" ] [] |> should equal <| _div [ Attr.form "falco" ] []
    _div [ _formaction_ "falco" ] [] |> should equal <| _div [ Attr.formaction "falco" ] []
    _div [ _formenctype_ "falco" ] [] |> should equal <| _div [ Attr.formenctype "falco" ] []
    _div [ _formmethod_ "falco" ] [] |> should equal <| _div [ Attr.formmethod "falco" ] []
    _div [ _formnovalidate_ ] [] |> should equal <| _div [ Attr.formnovalidate ] []
    _div [ _formtarget_ "falco" ] [] |> should equal <| _div [ Attr.formtarget "falco" ] []
    _div [ _headers_ "falco" ] [] |> should equal <| _div [ Attr.headers "falco" ] []
    _div [ _height_ "falco" ] [] |> should equal <| _div [ Attr.height "falco" ] []
    _div [ _hidden_ ] [] |> should equal <| _div [ Attr.hidden ] []
    _div [ _high_ "falco" ] [] |> should equal <| _div [ Attr.high "falco" ] []
    _div [ _href_ "falco" ] [] |> should equal <| _div [ Attr.href "falco" ] []
    _div [ _hreflang_ "falco" ] [] |> should equal <| _div [ Attr.hreflang "falco" ] []
    _div [ _httpEquiv_ "falco" ] [] |> should equal <| _div [ Attr.httpEquiv "falco" ] []
    _div [ _icon_ "falco" ] [] |> should equal <| _div [ Attr.icon "falco" ] []
    _div [ _id_ "falco" ] [] |> should equal <| _div [ Attr.id "falco" ] []
    _div [ _importance_ "falco" ] [] |> should equal <| _div [ Attr.importance "falco" ] []
    _div [ _integrity_ "falco" ] [] |> should equal <| _div [ Attr.integrity "falco" ] []
    _div [ _inputmode_ "falco" ] [] |> should equal <| _div [ Attr.inputmode "falco" ] []
    _div [ _ismap_ ] [] |> should equal <| _div [ Attr.ismap ] []
    _div [ _itemprop_ "falco" ] [] |> should equal <| _div [ Attr.itemprop "falco" ] []
    _div [ _keytype_ "falco" ] [] |> should equal <| _div [ Attr.keytype "falco" ] []
    _div [ _kind_ "falco" ] [] |> should equal <| _div [ Attr.kind "falco" ] []
    _div [ _label_ "falco" ] [] |> should equal <| _div [ Attr.label "falco" ] []
    _div [ _lang_ "falco" ] [] |> should equal <| _div [ Attr.lang "falco" ] []
    _div [ _loading_ "falco" ] [] |> should equal <| _div [ Attr.loading "falco" ] []
    _div [ _list_ "falco" ] [] |> should equal <| _div [ Attr.list "falco" ] []
    _div [ _loop_ ] [] |> should equal <| _div [ Attr.loop ] []
    _div [ _low_ "falco" ] [] |> should equal <| _div [ Attr.low "falco" ] []
    _div [ _max_ "falco" ] [] |> should equal <| _div [ Attr.max "falco" ] []
    _div [ _maxlength_ "falco" ] [] |> should equal <| _div [ Attr.maxlength "falco" ] []
    _div [ _minlength_ "falco" ] [] |> should equal <| _div [ Attr.minlength "falco" ] []
    _div [ _media_ "falco" ] [] |> should equal <| _div [ Attr.media "falco" ] []
    _div [ _method_ "falco" ] [] |> should equal <| _div [ Attr.method "falco" ] []
    _div [ _min_ "falco" ] [] |> should equal <| _div [ Attr.min "falco" ] []
    _div [ _multiple_ ] [] |> should equal <| _div [ Attr.multiple ] []
    _div [ _muted_ ] [] |> should equal <| _div [ Attr.muted ] []
    _div [ _name_ "falco" ] [] |> should equal <| _div [ Attr.name "falco" ] []
    _div [ _novalidate_ ] [] |> should equal <| _div [ Attr.novalidate ] []
    _div [ _open_ "falco" ] [] |> should equal <| _div [ Attr.open' "falco" ] []
    _div [ _optimum_ "falco" ] [] |> should equal <| _div [ Attr.optimum "falco" ] []
    _div [ _pattern_ "falco" ] [] |> should equal <| _div [ Attr.pattern "falco" ] []
    _div [ _ping_ "falco" ] [] |> should equal <| _div [ Attr.ping "falco" ] []
    _div [ _placeholder_ "falco" ] [] |> should equal <| _div [ Attr.placeholder "falco" ] []
    _div [ _poster_ "falco" ] [] |> should equal <| _div [ Attr.poster "falco" ] []
    _div [ _preload_ "falco" ] [] |> should equal <| _div [ Attr.preload "falco" ] []
    _div [ _radiogroup_ "falco" ] [] |> should equal <| _div [ Attr.radiogroup "falco" ] []
    _div [ _readonly_ ] [] |> should equal <| _div [ Attr.readonly ] []
    _div [ _referrerpolicy_ "falco" ] [] |> should equal <| _div [ Attr.referrerpolicy "falco" ] []
    _div [ _rel_ "falco" ] [] |> should equal <| _div [ Attr.rel "falco" ] []
    _div [ _required_ ] [] |> should equal <| _div [ Attr.required ] []
    _div [ _reversed_ ] [] |> should equal <| _div [ Attr.reversed ] []
    _div [ _role_ "falco" ] [] |> should equal <| _div [ Attr.role "falco" ] []
    _div [ _rows_ "falco" ] [] |> should equal <| _div [ Attr.rows "falco" ] []
    _div [ _rowspan_ "falco" ] [] |> should equal <| _div [ Attr.rowspan "falco" ] []
    _div [ _sandbox_ "falco" ] [] |> should equal <| _div [ Attr.sandbox "falco" ] []
    _div [ _scope_ "falco" ] [] |> should equal <| _div [ Attr.scope "falco" ] []
    _div [ _selected_ ] [] |> should equal <| _div [ Attr.selected ] []
    _div [ _shape_ "falco" ] [] |> should equal <| _div [ Attr.shape "falco" ] []
    _div [ _size_ "falco" ] [] |> should equal <| _div [ Attr.size "falco" ] []
    _div [ _sizes_ "falco" ] [] |> should equal <| _div [ Attr.sizes "falco" ] []
    _div [ _slot_ "falco" ] [] |> should equal <| _div [ Attr.slot "falco" ] []
    _div [ _span_ "falco" ] [] |> should equal <| _div [ Attr.span "falco" ] []
    _div [ _spellcheck_ "falco" ] [] |> should equal <| _div [ Attr.spellcheck "falco" ] []
    _div [ _src_ "falco" ] [] |> should equal <| _div [ Attr.src "falco" ] []
    _div [ _srcdoc_ "falco" ] [] |> should equal <| _div [ Attr.srcdoc "falco" ] []
    _div [ _srclang_ "falco" ] [] |> should equal <| _div [ Attr.srclang "falco" ] []
    _div [ _srcset_ "falco" ] [] |> should equal <| _div [ Attr.srcset "falco" ] []
    _div [ _start_ "falco" ] [] |> should equal <| _div [ Attr.start "falco" ] []
    _div [ _step_ "falco" ] [] |> should equal <| _div [ Attr.step "falco" ] []
    _div [ _style_ "falco" ] [] |> should equal <| _div [ Attr.style "falco" ] []
    _div [ _tabindex_ "falco" ] [] |> should equal <| _div [ Attr.tabindex "falco" ] []
    _div [ _target_ "falco" ] [] |> should equal <| _div [ Attr.target "falco" ] []
    _div [ _title_ "falco" ] [] |> should equal <| _div [ Attr.title "falco" ] []
    _div [ _translate_ "falco" ] [] |> should equal <| _div [ Attr.translate "falco" ] []
    _div [ _type_ "falco" ] [] |> should equal <| _div [ Attr.type' "falco" ] []
    _div [ _usemap_ "falco" ] [] |> should equal <| _div [ Attr.usemap "falco" ] []
    _div [ _value_ "falco" ] [] |> should equal <| _div [ Attr.value "falco" ] []
    _div [ _width_ "falco" ] [] |> should equal <| _div [ Attr.width "falco" ] []
    _div [ _wrap_ "falco" ] [] |> should equal <| _div [ Attr.wrap "falco" ] []
    _div [ _onabort_ "falco" ] [] |> should equal <| _div [ Attr.onabort "falco" ] []
    _div [ _onafterprint_ "falco" ] [] |> should equal <| _div [ Attr.onafterprint "falco" ] []
    _div [ _onanimationend_ "falco" ] [] |> should equal <| _div [ Attr.onanimationend "falco" ] []
    _div [ _onanimationiteration_ "falco" ] [] |> should equal <| _div [ Attr.onanimationiteration "falco" ] []
    _div [ _onanimationstart_ "falco" ] [] |> should equal <| _div [ Attr.onanimationstart "falco" ] []
    _div [ _onbeforeprint_ "falco" ] [] |> should equal <| _div [ Attr.onbeforeprint "falco" ] []
    _div [ _onbeforeunload_ "falco" ] [] |> should equal <| _div [ Attr.onbeforeunload "falco" ] []
    _div [ _onblur_ "falco" ] [] |> should equal <| _div [ Attr.onblur "falco" ] []
    _div [ _oncanplay_ "falco" ] [] |> should equal <| _div [ Attr.oncanplay "falco" ] []
    _div [ _oncanplaythrough_ "falco" ] [] |> should equal <| _div [ Attr.oncanplaythrough "falco" ] []
    _div [ _onchange_ "falco" ] [] |> should equal <| _div [ Attr.onchange "falco" ] []
    _div [ _onclick_ "falco" ] [] |> should equal <| _div [ Attr.onclick "falco" ] []
    _div [ _oncontextmenu_ "falco" ] [] |> should equal <| _div [ Attr.oncontextmenu "falco" ] []
    _div [ _oncopy_ "falco" ] [] |> should equal <| _div [ Attr.oncopy "falco" ] []
    _div [ _oncut_ "falco" ] [] |> should equal <| _div [ Attr.oncut "falco" ] []
    _div [ _ondblclick_ "falco" ] [] |> should equal <| _div [ Attr.ondblclick "falco" ] []
    _div [ _ondrag_ "falco" ] [] |> should equal <| _div [ Attr.ondrag "falco" ] []
    _div [ _ondragend_ "falco" ] [] |> should equal <| _div [ Attr.ondragend "falco" ] []
    _div [ _ondragenter_ "falco" ] [] |> should equal <| _div [ Attr.ondragenter "falco" ] []
    _div [ _ondragleave_ "falco" ] [] |> should equal <| _div [ Attr.ondragleave "falco" ] []
    _div [ _ondragover_ "falco" ] [] |> should equal <| _div [ Attr.ondragover "falco" ] []
    _div [ _ondragstart_ "falco" ] [] |> should equal <| _div [ Attr.ondragstart "falco" ] []
    _div [ _ondrop_ "falco" ] [] |> should equal <| _div [ Attr.ondrop "falco" ] []
    _div [ _ondurationchange_ "falco" ] [] |> should equal <| _div [ Attr.ondurationchange "falco" ] []
    _div [ _onemptied_ "falco" ] [] |> should equal <| _div [ Attr.onemptied "falco" ] []
    _div [ _onended_ "falco" ] [] |> should equal <| _div [ Attr.onended "falco" ] []
    _div [ _onerror_ "falco" ] [] |> should equal <| _div [ Attr.onerror "falco" ] []
    _div [ _onfocus_ "falco" ] [] |> should equal <| _div [ Attr.onfocus "falco" ] []
    _div [ _onformchange_ "falco" ] [] |> should equal <| _div [ Attr.onformchange "falco" ] []
    _div [ _onforminput_ "falco" ] [] |> should equal <| _div [ Attr.onforminput "falco" ] []
    _div [ _onfocusin_ "falco" ] [] |> should equal <| _div [ Attr.onfocusin "falco" ] []
    _div [ _onfocusout_ "falco" ] [] |> should equal <| _div [ Attr.onfocusout "falco" ] []
    _div [ _onfullscreenchange_ "falco" ] [] |> should equal <| _div [ Attr.onfullscreenchange "falco" ] []
    _div [ _onfullscreenerror_ "falco" ] [] |> should equal <| _div [ Attr.onfullscreenerror "falco" ] []
    _div [ _onhashchange_ "falco" ] [] |> should equal <| _div [ Attr.onhashchange "falco" ] []
    _div [ _oninput_ "falco" ] [] |> should equal <| _div [ Attr.oninput "falco" ] []
    _div [ _oninvalid_ "falco" ] [] |> should equal <| _div [ Attr.oninvalid "falco" ] []
    _div [ _onkeydown_ "falco" ] [] |> should equal <| _div [ Attr.onkeydown "falco" ] []
    _div [ _onkeypress_ "falco" ] [] |> should equal <| _div [ Attr.onkeypress "falco" ] []
    _div [ _onkeyup_ "falco" ] [] |> should equal <| _div [ Attr.onkeyup "falco" ] []
    _div [ _onload_ "falco" ] [] |> should equal <| _div [ Attr.onload "falco" ] []
    _div [ _onloadeddata_ "falco" ] [] |> should equal <| _div [ Attr.onloadeddata "falco" ] []
    _div [ _onloadedmetadata_ "falco" ] [] |> should equal <| _div [ Attr.onloadedmetadata "falco" ] []
    _div [ _onloadstart_ "falco" ] [] |> should equal <| _div [ Attr.onloadstart "falco" ] []
    _div [ _onmessage_ "falco" ] [] |> should equal <| _div [ Attr.onmessage "falco" ] []
    _div [ _onmousedown_ "falco" ] [] |> should equal <| _div [ Attr.onmousedown "falco" ] []
    _div [ _onmouseenter_ "falco" ] [] |> should equal <| _div [ Attr.onmouseenter "falco" ] []
    _div [ _onmouseleave_ "falco" ] [] |> should equal <| _div [ Attr.onmouseleave "falco" ] []
    _div [ _onmousemove_ "falco" ] [] |> should equal <| _div [ Attr.onmousemove "falco" ] []
    _div [ _onmouseover_ "falco" ] [] |> should equal <| _div [ Attr.onmouseover "falco" ] []
    _div [ _onmouseout_ "falco" ] [] |> should equal <| _div [ Attr.onmouseout "falco" ] []
    _div [ _onmouseup_ "falco" ] [] |> should equal <| _div [ Attr.onmouseup "falco" ] []
    _div [ _onmousewheel_ "falco" ] [] |> should equal <| _div [ Attr.onmousewheel "falco" ] []
    _div [ _onoffline_ "falco" ] [] |> should equal <| _div [ Attr.onoffline "falco" ] []
    _div [ _ononline_ "falco" ] [] |> should equal <| _div [ Attr.ononline "falco" ] []
    _div [ _onopen_ "falco" ] [] |> should equal <| _div [ Attr.onopen "falco" ] []
    _div [ _onpagehide_ "falco" ] [] |> should equal <| _div [ Attr.onpagehide "falco" ] []
    _div [ _onpageshow_ "falco" ] [] |> should equal <| _div [ Attr.onpageshow "falco" ] []
    _div [ _onpaste_ "falco" ] [] |> should equal <| _div [ Attr.onpaste "falco" ] []
    _div [ _onpause_ "falco" ] [] |> should equal <| _div [ Attr.onpause "falco" ] []
    _div [ _onplay_ "falco" ] [] |> should equal <| _div [ Attr.onplay "falco" ] []
    _div [ _onplaying_ "falco" ] [] |> should equal <| _div [ Attr.onplaying "falco" ] []
    _div [ _onpopstate_ "falco" ] [] |> should equal <| _div [ Attr.onpopstate "falco" ] []
    _div [ _onprogress_ "falco" ] [] |> should equal <| _div [ Attr.onprogress "falco" ] []
    _div [ _onratechange_ "falco" ] [] |> should equal <| _div [ Attr.onratechange "falco" ] []
    _div [ _onresize_ "falco" ] [] |> should equal <| _div [ Attr.onresize "falco" ] []
    _div [ _onreset_ "falco" ] [] |> should equal <| _div [ Attr.onreset "falco" ] []
    _div [ _onscroll_ "falco" ] [] |> should equal <| _div [ Attr.onscroll "falco" ] []
    _div [ _onsearch_ "falco" ] [] |> should equal <| _div [ Attr.onsearch "falco" ] []
    _div [ _onseeked_ "falco" ] [] |> should equal <| _div [ Attr.onseeked "falco" ] []
    _div [ _onseeking_ "falco" ] [] |> should equal <| _div [ Attr.onseeking "falco" ] []
    _div [ _onselect_ "falco" ] [] |> should equal <| _div [ Attr.onselect "falco" ] []
    _div [ _onshow_ "falco" ] [] |> should equal <| _div [ Attr.onshow "falco" ] []
    _div [ _onstalled_ "falco" ] [] |> should equal <| _div [ Attr.onstalled "falco" ] []
    _div [ _onstorage_ "falco" ] [] |> should equal <| _div [ Attr.onstorage "falco" ] []
    _div [ _onsubmit_ "falco" ] [] |> should equal <| _div [ Attr.onsubmit "falco" ] []
    _div [ _onsuspend_ "falco" ] [] |> should equal <| _div [ Attr.onsuspend "falco" ] []
    _div [ _ontimeupdate_ "falco" ] [] |> should equal <| _div [ Attr.ontimeupdate "falco" ] []
    _div [ _ontoggle_ "falco" ] [] |> should equal <| _div [ Attr.ontoggle "falco" ] []
    _div [ _ontouchcancel_ "falco" ] [] |> should equal <| _div [ Attr.ontouchcancel "falco" ] []
    _div [ _ontouchend_ "falco" ] [] |> should equal <| _div [ Attr.ontouchend "falco" ] []
    _div [ _ontouchmove_ "falco" ] [] |> should equal <| _div [ Attr.ontouchmove "falco" ] []
    _div [ _ontouchstart_ "falco" ] [] |> should equal <| _div [ Attr.ontouchstart "falco" ] []
    _div [ _ontransitionend_ "falco" ] [] |> should equal <| _div [ Attr.ontransitionend "falco" ] []
    _div [ _onunload_ "falco" ] [] |> should equal <| _div [ Attr.onunload "falco" ] []
    _div [ _onvolumechange_ "falco" ] [] |> should equal <| _div [ Attr.onvolumechange "falco" ] []
    _div [ _onwaiting_ "falco" ] [] |> should equal <| _div [ Attr.onwaiting "falco" ] []
    _div [ _onwheel_ "falco" ] [] |> should equal <| _div [ Attr.onwheel "falco" ] []
