name: build

on:
  push:
    branches: [master]
    # exclude commits
    paths-ignore:
      - 'README.md'

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['8.0.x']
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Install dependencies
        run: dotnet restore src/Falco.Markup

      - name: Build
        run: dotnet build src/Falco.Markup -c Release

      - name: Test
        run: dotnet test test/Falco.Markup.Tests -c Release
